- Using-Mastodon/Apps.md
A project about various tools including a Wordpress plugin, now ready to download at wordpress.org
> Add mastodon.tools

- Running-Mastodon/Production-guide.md
most of the nginx example config is safe to copy and paste, it will either work or not but it won't break anything, but a HSTS header with includeSubDomains, cached for a year, will break anything hosted on a subdomain that does not have https, and it is hard to undo
considering mastodon only uses the one domain, i don't think it should bother itself with whether subdomains have HSTS or not
> example nginx: remove includeSubDomains from hsts

- Using-Mastodon/Apps.md
Retoot is a small CLI tool to mirror tweets to mastodon accounts
> Add Retoot tool

- Running-Mastodon/Production-guide.md
Sidekiq only listens on v4 and using localhost will create
non-usable connections to ::1
Re-creating my earlier pull request from the main repo as requested - https://github.com/tootsuite/mastodon/pull/1313#issuecomment-293331562
> Use 127.0.0.1 instead of localhost in Sidekiq proxy_pass.

- Running-Mastodon/Production-guide.md
Intended to avoid setting duplicate HTTP headers which will cause issues with tools like Mozilla Observatory many people use to evaluate an instance's security.
> Add info about already set HTTP headers

- Using-Mastodon/List-of-Mastodon-instances.md
Reverts tootsuite/documentation#21
Oulipo.social's IPv6 DOES NOT WORK :
> Revert "Oulipo.social has IPv6 now"

- Using-the-API/API.md
The follow and unfollow methods are POST, not GET.
```console
$ RAILS_ENV=production rails routes
...
follow_api_v1_account POST   /api/v1/accounts/:id/follow(.:format)                api/v1/accounts#follow
unfollow_api_v1_account POST   /api/v1/accounts/:id/unfollow(.:format)              api/v1/accounts#unfollow
```
Also, the returned JSON is below.
```
{id: 1, following: true, followed_by: true, blocking: false, muting: false, requested: false}
{id: 1, following: false, followed_by: true, blocking: false, muting: false, requested: false}
```
This is a Relationship.
> Fix follow and unfollow api documents

- Using-Mastodon/List-of-Mastodon-instances.md
Bonn.social is a mastodon-server from Bonn, Germany
> Adding of Bonn.social

- Using-the-API/API.md
Since the item of ID was included in Relationship, it added.
```
$ curl -X POST -H 'Authorization: Bearer xxxTOKENxxx' https://mstdn.jp/api/v1/accounts/4880/follow
{"id":4880,"following":true,"followed_by":true,"blocking":false,"muting":false,"requested":false}
$ curl -X POST -H 'Authorization: Bearer xxxTOKENxxx' https://mstdn.jp/api/v1/accounts/4880/unfollow
{"id":4880,"following":false,"followed_by":true,"blocking":false,"muting":false,"requested":false}
```
> Add id to Relationship

- Using-the-API/API.md
When I got, the order of account entities was below.
```console
$ curl -H 'Authorization:Bearer xxxTOKENxxx' https://example.com/api/v1/accounts/1
{
"id": 1,
"username": "foo",
"acct": "foo",
"display_name": "bar",
"locked": false,
"created_at": "2017-04-14T12:38:26.726Z",
"followers_count": 123,
"following_count": 456,
"statuses_count": 789,
"note": "Hello, World!",
"url": "https://example.com/@foo",
"avatar": "https://img.example.com/accounts/avatars/000/000/186/original/55a4b1361703b60b.png?1492173581",
"avatar_static": "https://img.example.com/accounts/avatars/000/000/186/original/55a4b1361703b60b.png?1492173581",
"header": "/headers/original/missing.png",
"header_static": "/headers/original/missing.png"
}
```
So I fixed the order.
The account provides a static image of the gif image. …
> Fix account entities

- Using-the-API/API.md
This is the same error as in https://github.com/tootsuite/documentation/commit/218a1a2444d6ed8fbb0ef8151c2ade3a19663648, originally fixed by https://github.com/tootsuite/documentation/commit/581d62ea7723b8b491c65868e99105532bec986a but (accidentally?) reverted by https://github.com/tootsuite/documentation/commit/eebeee2b76f269cd26e420cbe78467ae8f824749
> API documentation fix for blocking/muting

- Using-Mastodon/List-of-Mastodon-instances.md
Since links to this page are everywhere, putting the message about it status at the top, and emphasising the link to xyz.
> Updated unmaintened message in instances list

- Running-Mastodon/Heroku-guide.md
I've updated Heroku docs to correspond with this pull request: https://github.com/tootsuite/mastodon/pull/1873 This change is made based on a conversation [here](https://github.com/tootsuite/mastodon/pull/1363).
> Added recommendation against running free dynos in production.

- Using-the-API/API.md
The URL interface of follow_requests was incorrect.
It is correctly the interface including the ID.
```console
$ RAILS_ENV=production rails routes
...
authorize_api_v1_follow_request POST   /api/v1/follow_requests/:id/authorize(.:format)      api/v1/follow_requests#authorize
reject_api_v1_follow_request POST   /api/v1/follow_requests/:id/reject(.:format)         api/v1/follow_requests#reject
```
> Fix follow_requests api path interface

- Using-Mastodon/Apps.md
Toot is a CLI interface to Mastodon written in Python.
> Add toot to applications

- Running-Mastodon/Development-guide.md
Adds a mention of `yarn install` in the development guide so people know to, well, run it.
> Mention Yarn in Dev Docs

- README.md
- Running-Mastodon/Docker-Guide.md
This updates a broken link on the `Docker-Guide` page, and fixes a typo "ressources" => "resources"
> Update link, fix typo

- Using-the-API/API.md
`id` is a Parameters, not Form data.
> Fix follow requests API description

- Running-Mastodon/Production-guide.md
If JavaScript dependencies have changed in between versions, `yarn install` needs to be run to update those. Otherwise, library API changes might break production (this has happened to me after [a new dependency](https://github.com/tootsuite/mastodon/commit/b22b2cbfacdaef2441d14f401c95863d8ca2e66c) on `node-http-link`'s `Link.parseParameters`).
Also specify that web workers need to be restarted also for precompiled asset changes.
> Mention `yarn install` in production upgrade guide

- Running-Mastodon/Heroku-guide.md
Just a small tweak to fix the sample IAM policy in the docs.
> Fix bad quote char in IAM policy

- Running-Mastodon/Administration-guide.md
It's useful to be able to sidestep closed registration without opening registration for users, so having a quick section on this seems pretty useful.
> Add administration section on how to create users while registration is closed

- Using-Mastodon/Apps.md
Mastodon Lang Remover is a Tampermonkey script, detecting langage and remove toots using lang specified.
> Adding Mastodon Lang Remover

- Running-Mastodon/Tuning.md
* Ruby 1.9+ uses native threads.
* Puma workers do share some memory via copy-on-write.
* A Sidekiq concurrency of 5 doesn't necessarily mean 5 jobs can be processed simultaneously.
Rather than attempt a complete explanation of the GIL in this documentation, I thought I'd just remove/alter some of the inaccurate statements.
> Make tuning.md a little more accurate

- Using-Mastodon/Apps.md
Hi
Last few days, I made a tiny web-based desktop client for Mastodon. It runs on macOS, Windows or Linux because I made it with Electron framework.
App URL:
https://github.com/rhysd/Mstdn
> Add Mstdn to apps

- Running-Mastodon/Production-guide.md
To further increase security add a strong Diffie-Hellman group, which is standard practice when setting up ssl certs. Anyone who can setup letsencrypt can also setup a DH group.
> update nginx ssl config

- Running-Mastodon/Docker-Guide.md
This seems to have caught some folks, but by default the `docker-compose.yml` specifies no persistence for databases. This PR draws attention to that fact.
Fixes https://github.com/tootsuite/mastodon/issues/1376 . Fixes https://github.com/tootsuite/mastodon/issues/1475 .
> Adds note about persisting volumes.

- Using-Mastodon/FAQ.md
An append to the FAQ.md containing actual questions asked in the fediverse. I have more from @raccoon@awoo.space (https://hastebin.com/raw/xuqogukimu), but I'm waiting for a recent version. Also, the images are remote (served by octodon.social), and probably should be moved to the repo if accepted.
> Add to FAQ.md the questions asked by users in the Fediverse

- Running-Mastodon/Production-guide.md
AFAICT there's no reason not to serve static assets directly from nginx, so this seems like a reasonable recommendation for the official docs.
I also added a high enough cache time and `cache-control:immutable` because all these resources have their checksums in the names, so they can essentially be cached indefinitely. `cache-control:immutable` is in Firefox 49+ and Edge 15 and causes the browser to skip an unnecessary revalidation request even when hitting reload/F5 ([details here](https://hacks.mozilla.org/2017/01/using-immutable-caching-to-speed-up-the-web/)). Chrome doesn't have this but it has a heuristic, and I confirmed that 31536000 (365 days) matches the heuristic so it avoids the revalidation as well.
> Add nginx config for static assets

- Using-the-API/API.md
Adds documentation for the API that was added in https://github.com/tootsuite/mastodon/pull/2251.
> Add documentation for /api/v1/notifications/dismiss

- Running-Mastodon/Development-guide.md
- Running-Mastodon/Production-guide.md
Without the `--pure-lockfile` option, the `yarn.lock` file will be updated.
> Add yarn install option

- Using-Mastodon/Apps.md
Add Pawoo, an Android client for Mastodon - a little customized for pawoo.net :-)
> Add Pawoo Android app to Apps.md

- README.md
There's not a great place to put this, since documentation for various deployment strategies is so disperse and various, so I put it here. It's important, and would help a lot with GitHub issues and user-facing bugs.
> Adds note about running off master.

- Contributing-to-Mastodon/Translating-Github-Cheat-Sheet.md
Dealing with `git` is holding back translations from some Mastodon users. This PR currently covers the general workflow a translator might encounter.
It is missing:
- How to properly deal with your copy/fork getting behind (workaround is just to delete everything except translated files)
- What this workflow looks like if you are a contributor to Mastodon (leaving this out might be okay)
- How to create and use a branch on your own fork (leaving this out might be okay)
> Added quick documentation on forking/pulling/pushing/submiting a PR

- Using-the-API/API.md
This is a clarification for tootsuite/mastodon#2273
I have passed on all APIs with curl to find those that do not require authentication with a token.
> Mark all APIs that do not require authentication

- Contributing-to-Mastodon/Translating.md
The two links mentioned here are mostly official places for parking these libraries' translations. Pointing translators there should save them some time.
> Translating: add devise/doorkeeper i18n sources

- Contributing-to-Mastodon/Translating.md
Paths getting pretty long here. Wondering if Mastodon should look into the [devise-i18n](https://github.com/tigrish/devise-i18n) gem. And sorry for all the line `<br>`eaks added.
> Translating: add devise email templates, fix #123

- Running-Mastodon/Production-guide.md
This change allows OpenSSL to choose the most appropriate available cipher(s) from the HIGH cipher suite. This is sufficient to get an A on the SSLLabs.com tests suite. If MEDIUM is allowed as well, the grade drops to a B which is still more than adequate for most deployments.
This type of configuration would prevent problems such as the current inability of Tusky on Android 7 devices to connect to some Mastodon instances.
The main benefit though, is this delegates the decisions about which ciphers are "good" and which ciphers are "bad" to the experts; the distribution security teams and the OpenSSL developers. If a weakness is found in a particular cipher it will get moved from HIGH to one of the lower classes (or removed entirely) and this will get deployed just like any other security …
> Avoid hard-coding ciphers into configuration

- Running-Mastodon/Maintenance-Tasks.md
These tasks sometimes fail under non-Docker installations when the administrator tries to run them without explicitly requesting the production environment.
> Include explicit production environment

- Running-Mastodon/Production-guide.md
I can't think of any reason not to enable HTTP/2. It has nearly [universal support](http://caniuse.com/#feat=http2), including IE11 which Mastodon doesn't appear to support anyway due to missing an `Object.assign` polyfill. Been testing toot.cafe on H2 with Safari, Edge, Chrome, and Firefox, and everything looks A-OK. :smiley:
> Recommend HTTP/2 in the nginx config

- Running-Mastodon/Production-guide.md
The files under `system/media_attachments/files` and `system/accounts/avatars` also appear to be uniquely identified by their filename, so it should be safe to increase the cache for these. I'm running this in production right now on toot.cafe and it's working well so far.
> Add photos and avatars to static/immutable cache

- Using-Mastodon/FAQ.md
Addressing #153
Should this be part of the FAQ or should it be under the 'running Mastodon' documentation tree?
> Adding FAQ regarding default upload size limit

- Running-Mastodon/Serving_a_different_domain.md
Since Mastodon v1.3.0, federation with instances having WEB_DOMAIN ≠ LOCAL_DOMAIN is severly broken, see https://github.com/tootsuite/mastodon/issues/2672
> Add note on PuSH issue with Mastodon v1.3.2

- Running-Mastodon/Vagrant-guide.md
Updated the vagrant guide since the start-up method has changed in the following pull request.
https://github.com/tootsuite/mastodon/pull/2742
> update how to launch application with vagrant

- Using-the-API/API.md
The text always specified "Maximum number of accounts" instead of
naming the object that was actually being retrieved such as statuses
or blocks.
> Fix various instances of "Maximum number of"

- Using-Mastodon/Apps.md
This PR adds my UWP Mastodon app, WinMasto, to Apps.md.
> Add WinMasto to Apps.md

- Running-Mastodon/Production-guide.md
`sudo su` limits the capability of sudo to log the operations. `-u` option is more straightforward and has better logging.
> Use "sudo -u" instead of "sudo su"

- Running-Mastodon/Administration-guide.md
Identical line about turning user into an admin via Docker is just below
> Remove duplicate line in Administration guide

- Running-Mastodon/Production-guide.md
Follow up to https://github.com/tootsuite/documentation/pull/127, with the goal of addressing the concerns in https://github.com/tootsuite/documentation/pull/127#issuecomment-297661478.
This is what we're currently running on toot.cafe and doesn't seem to cause any issues. Scores an A- on Mozilla Observatory – AFAICT it's not possible to score A+ because removing `script-src 'unsafe-inline'` will result in a console error in Firefox.
I think it's important to at least have a default recommended CSP because a lot of instances seem to be rolling their own, which can cause compat issues, e.g. there was discussion [on Matrix](https://matrix.to/#/!VMUpuubSCTxMbZkuZa:cybre.space/$1493869579852685YXIjI:matrix.org) about mst3k federation being broken due to a bad CSP.
> Add default CSP (take 2)

- Using-the-API/API.md
It helps developers building applications and libraries.
> Adds nullability information to entities

- Running-Mastodon/Production-guide.md
According to the conversation in f0a863feecd4b138520, Debian 8 installs an older version of nginx by default. This adds a note telling administrators how to install a newer version.
> Add a Debian 8 installation note

- Using-the-API/API.md
Arrays _have_ to be passed with empty square brackets, otherwise the API returns an error.
For instance https://github.com/MastodonKit/MastodonKit/blob/master/Tests/MastodonKitTests/Resources/ReportsTests.swift#L34
> Changes on ruby arrays as parameters

- Using-the-API/API.md
`text_url` can be `null` for remote images
> Fixed nullability for `Attachment.text_url`

- Using-Mastodon/Apps.md
I made mastodon-glossary-bot because I could not find an equivalent to codeforamerica/glossary-bot. It is already used at https://mastodon.etalab.gouv.fr, however it is still very experimental. Hope you find it interesting enough to join the list. Otherwise I am hungry for advise to improve it.
> Add mastodon-glossary-bot

- README.md
- Using-the-API/API.md
- Using-the-API/Libraries.md
The list of libraries is getting bigger and bigger. To keep the API documentation clean and specific, I'm moving the list of libraries to its own page.
> Moves libraries to a separate file

- Running-Mastodon/Production-guide.md
Added a note about having to add Debian Backports repository to properly install `ffmpeg`.
> Added note about adding backports on Debian.

- Using-the-API/API.md
The API works correctly when ```resolve``` is not specified. Let's fix this.
> Fix optionality of resolve

- Using-the-API/API.md
The API.md document should reflect the currently API version and, for the current version, Mastodon's version is always present. Therefore, the version attribute it's not nullable.
> Reflects the latest API version

- Running-Mastodon/Production-guide.md
In Debian the package `pkg-config` is required to install the rubygem `cld3`.
> Needed pkg-config to install cld3.

- Using-the-API/API.md
`id` is neither a query item (GET) nor part of the body (POST), therefore should not be in the parameter table.
> Removes id parameter from documentation

- Running-Mastodon/Vagrant-guide.md
When a provider other than virtualbox is registered in Vagrant, `vagrant up` can not start Mastodon.
For example, it corresponds to the environment where Parallels Desktop is installed.
> Explicitly use --provider option for vagrant up

- Running-Mastodon/Docker-Guide.md
This change will help users avoid unnecessary procedure to
complete `bundle install` outside the container.
The explanation
> To generate the PAPERCLIP_SECRET, SECRET_KEY_BASE, and
> OTP_SECRET, you may use:
>
> ```
> rake secret
> ```
gives users a false impression that secrets have to be filled in
before the image can be built. Here, with introduction of CLD3,
completion of `bundle install` became more involved procedure to
prepare tools and libraries as well as higher version of Ruby.
> Remove the procedure to run `rake secret` outside the container

- Using-the-API/API.md
All the paginable models use [the same pagination method with "id < max_id" condition](https://github.com/tootsuite/mastodon/blob/defe4f9bc3407cde4d5b1918778b0754ef7f4970/app/models/concerns/paginable.rb#L9), so the descriptions should be "less than" and not "less than or equal".
Can be easily checked with curl too.
> fix max_id description

- Running-Mastodon/Production-guide.md
If you're omitting RAILS_ENV and `bundle exec` you'll have:
~~~
rake aborted!                             
NameError: uninitialized constant Annotate
[…]
~~~
> Missing RAILS_ENV=production and bundle exec

- Running-Mastodon/Production-guide.md
The git tag command was incorrectly checking out release candidates instead of the latest release. Fixes #309
> Update command to checkout latest release.

- Using-the-API/API.md
a potential resolution to tootsuite/mastodon#3804, achieved by not
encouraging people to use upload methods without filenames
my rationale for this being the right solution is that it brings it to
parity with the media upload method, which has already proven to be
enough for library developers to understand. it should be enough that,
early in the docs, it says that 'When a file parameter is mentioned, a
form-encoded upload is expected.'
i wouldn't mind so much if the base64 upload method didn't expose such
an insidious bug, but even if it didn't, it seems reasonable to want to
encourage developers to upload all media in a consistent way
> don't encourage people to use base64 avatar and header image uploads

- Running-Mastodon/Production-guide.md
CentOS's repo does not have package named "g++", "gcc-c++" can be used instead.
On the other hand, there is no actual problem because it is installed later by `sudo yum group install "Development tools"`.
So I have just removed "g++".
> Remove unavailable package from General dependencies for CentOS / RHEL

- Running-Mastodon/Production-guide.md
Hi,
Since version 1.4.1, daily tasks are handled by `sidekiq-scheduler` with the exception of `mastodon:users:clear` (which I think can be run manually every now and then).
> Remove the cronjobs section from the production guide

- Running-Mastodon/Docker-Guide.md
I was reading [documentation/Docker\-Guide\.md](https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Docker-Guide.md) to run Mastodon with Docker.
I did not know which directory to execute the "Setting up" chapter.
With the following command I successfully proceeded to the next step.
```sh
git clone git@github.com:tootsuite/mastodon.git
cd mastodon
```
I started reading from the [mastodon/README\.md](https://github.com/tootsuite/mastodon/blob/master/README.md) and read the [Deployment](https://github.com/tootsuite/documentation#running-mastodon), [Docker guide](https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Docker-Guide.md), but I could not find this command anywhere.
> Add the first step to clone.

- Contributing-to-Mastodon/Translating.md
The title is pretty self explanatory here. This also fixes a typo on `language`
> Fix typo on `yarn manage:translation` occurrences

- Running-Mastodon/Maintenance-Tasks.md
This should be included in the documentation. I wasn't sure what sort of schedule it should be run on, so I didn't add a recommendation for one.
> Adds `mastodon:media:remove_silenced` rake task

- Using-Mastodon/Apps.md
Sailfish OS client "Tooter" added to the list.
https://openrepos.net/content/dysko/tooter
Sources:
https://github.com/dysk0/harbour-tooter
> SailfishOS client added

- Running-Mastodon/Production-guide.md
Found this seemed to work better in my experience and also allows for easy updating like any other package.
Instructions taken from https://yarnpkg.com/en/docs/install
> Use the Yarn APT/YUM repository instead of npm

- Running-Mastodon/Production-guide.md
Pretty self-explanatory; apt won't be able to install yarn until we update.
> Update index after adding yarn repository

- Using-the-API/API.md
Use #relationship instead of #relationships.
> API.md: fix link to named anchor

- Running-Mastodon/Production-guide.md
Tested on Ubuntu Server 16.04.2 LTS
See: https://github.com/rbenv/ruby-build/wiki#trouble-with-irb-or-pry
> * Trouble with irb or pry
>
> Try installing readline and recompiling Ruby.
>
>     Ubuntu: apt-get install libreadline-dev
>     Fedora: yum install readline-devel
> `rbenv install 2.4.1` requires readline-devel

- Running-Mastodon/Production-guide.md
This is now required as of Mastodon v1.5.0+ due to idn-ruby.
> Add libidn11-dev to Ubuntu package dependencies

- Running-Mastodon/Production-guide.md
Some cases such as nginx uses reverse proxy, emoji will return 502 if not set.
+  sort by A-z.
> Add emoji files for nginx cache rules.

- Running-Mastodon/Production-guide.md
libicu-dev was added with v1.5.0, updating guide with this dependency.
> Add libicu-dev to Mastodon apt package list

- Using-Mastodon/Apps.md
I added my own small project for Mastodon. A sharing plugin for Mastodon, which you can install on your own server. I'd like to see some servers set up, so I can link them to my projects' repository.
> Added Mastoshare

- Running-Mastodon/Production-guide.md
Hello,
Here is some modifications made on this great guide:
- Nginx duplication in packages installation
- Specify the user type for `mastodon` (--system and --disabled-password)
- Simplify services start-up
- Clearly write how to check services are running (or not) with `systemctl status`
Cheers,
🤘🏻
> Fix some mistakes

- Running-Mastodon/Production-guide.md
Hello,
Here we can use only `git-core` in place of `git`. It's a small improvement but why not doing it? 😙
Cheers,
🤘🏻
> Reduce Git dependencies

- Running-Mastodon/Production-guide.md
Hello,
Curl need to be installed before the first time we use it. It's now installed before setting up `nodejs` repository.
Cheers,
🤘🏻
> Move curl installation

- Using-the-API/Libraries.md
Mastodon PHP API adapted to Wordpress HTTP API. (Replaced CURL with native commands)
This libary is licensed under the GPLv2. For concern of the original license the MIT licensefile is included, but is not applied to this project!
> Added Mastodon Wordpress API

- Running-Mastodon/Production-guide.md
VAPID keys are necessary for Web Push notifications to work.
Also fix a small typo.
> Add VAPID keys section to needed variables section 

- Running-Mastodon/Updating-Mastodon-Guide.md
``git tag -l | sort -V | head -1`` will consider release candidates as the latest version, even if there's a stable release, due to how `sort -V` orders strings. Adding ``grep -v 'rc[0-9]*$'`` to filter out the release candidate tags fixes this.
> Don't include RCs when checking out latest tag.

- Running-Mastodon/Production-guide.md
Fixing the same issue as d9e523ec15619ebd70f5b3fd279a2541c821c12f where the command is used in Production-guide.md
> Don't include RCs in initial setup

- Running-Mastodon/PgBouncer-guide.md
Double quotes are not syntactically correct here.
> Use single quotes for pg user password

- Using-the-API/API.md
Array for query parameter is now used only for this method, and I missed this explanation.
So this link may be helpful.
> Add reference to Array.

- Using-Mastodon/User-guide.md
- Using-Mastodon/User-guide_HUN.md
* Added Hungarian translation as a separate file following the naming convention of Spanish FAQ translation (User-guide_HUN.md)
* Added a reference link to the translation to the original file (User-guide.md)
* Added "Table of Contens" H2 header to the original file for better separation (User-guide.md)
> Add Hungarian translation for User Guide

- Using-Mastodon/Apps.md
Added Autopost to Mastodon Wordpress Plugin
https://wordpress.org/plugins/autopost-to-mastodon
> Autopost to Mastodon - Wordpress Plugin

- Running-Mastodon/Production-guide.md
This enables puma to reload changes without restarting process.
> add ExecReload to reload puma.

- Maintaining-Mastodon/Backups-Guide.md
This is a guide I wrote a couple months ago with a few suggestions on how to backup a Mastodon instance's data.
> Add Backups Guide

- Using-the-API/Libraries.md
TootNet is new Mastodon library for .NET Standard.
> Add TootNet to library list

- Running-Mastodon/Production-guide.md
This hashtag is not super active, but it is the de-facto one I've seen for debugging instance admin issues, so it seems worthwhile to mention: https://mastodon.social/tags/mastoadmins
> Add note about #MastoAdmins hashtag

- Running-Mastodon/Development-guide.md
This is a useful command that I think deserves a mention in the dev guide.
> Add snippet in dev guide about `yarn manage:translations`

- Running-Mastodon/Customizing.md
There was a missing "s" in the directory listing for source.rb
> Fix typo in Customizing.md

- Running-Mastodon/Production-guide.md
This gives some advice on getting started with an email service guide, including specifics on the process and caveats of the various free services people recommend, as well as a short command in the Rails console that helps a user test this out.
> Add email service guide in production-guide.md

- Using-the-API/API.md
Reblogging returns the reblog, not the target status.
> Fix reblog documentation bug

- Using-Mastodon/Apps.md
BirdSite is a browser extension for cross-posting toots to Twitter from the Mastodon web app.
_Disclaimer: I'm the author._
> Apps.md: add the BirdSite browser extension

- Running-Mastodon/Development-guide.md
The GNU/Linux setup works well but there are some OpenBSD-specific
considerations around default compilers, discovering third-party
libraries, and linker warnings.
> OpenBSD-specific development guide

- Using-Mastodon/Apps.md
The repo name did not change but the tool itself did.
> mastodon-backup renamed to mastodon-archive

- Using-the-API/API.md
It returns Lists, not Accounts.
> Fix /api/v1/accounts/:id/lists docs

- Using-the-API/API.md
The `description` field for the Attachment response object and the `pinned` field for the Status response object were missing from the API docs, so I've added them.
I'm not actually sure if `pinned` is nullable -- it doesn't seem like it is, but some other fields that also appeared non-nullable to me (`reblogged`, `favourited`) are in fact marked as nullable.
> Update API.md with some missing response fields

- Running-Mastodon/Development-guide.md
Moves the `libidn` installation command up to the big brew command to keep things consistent.
> Update Mac install instructions for consistency

- Using-the-API/API.md
`emojis` is not nullable. Instead, it returns an empty array when no emojis are used (which is consistent with other fields that return array of objects, for instance `media_attachments `, `mentions `, and `tags`).
```
"media_attachments": [],
"mentions": [],
"tags": [],
"emojis": []
```
> Updates Status.emojis information

- Using-the-API/API.md
Since they're not part of the `/api/v1/status*` family.
> Moves Custom Emojis do Instances

- Using-the-API/API.md
I should have fixed this before the previous PR. Sorry for the double work.
> Fixes typo (Lists -> List)

- Using-the-API/API.md
`following` parameter allows to search users for adding them to a list.
> Adds following parameter in /accounts/search

- Running-Mastodon/Alternatives.md
I had to add
```
Require all granted
```
today after installation in order for my mastodon instance to work.
otherwise there was no access to assets, no graphics on the registration page, nothing after registration.
> apache config fix.

- Running-Mastodon/Docker-Guide.md
Made clear there are two options for getting the Docker image: pulling the prebuilt image, or building your own. Using a prebuilt image is easier for anyone who hasn't made code changes on their instance.
> Clarify Docker instructions for prebuilt images

- Running-Mastodon/Production-guide.md
Reverts tootsuite/documentation#474
I'm sorry but providing a good-to-go nginx configuration is **absolutely necessary**. People can adjust their SSL stuff if they want, but this is a sufficient default. Also the PR seemed kind of mean-spirited.
> Revert #474

- Running-Mastodon/Development-guide.md
Based on the `.ruby-version` in the root of the Mastodon codebase and the "ruby-2.5.0 is not installed." message I got when changing to that directory I assume that the documentation should now instruct potential devs to install ruby 2.5.0.
> Update Mac instructions to have users install Ruby 2.5.0

- Running-Mastodon/Enabling-LDAP-login.md
I tried out the LDAP support in v2.3.0rc1, and wrote this document on how to set it up - it's not entirely straightforward, so I think benefits from good documentation.
> Add documentation on how to use LDAP for logins

- Running-Mastodon/Docker-Guide.md
db:setup is used in all guides except Docker Guide, which uses db:migrate
to create the database. db:setup is actually superior over db:migrate for
the purpose in terms of performance and compatibility.
db:setup is performant because it does not perform redundant migrations.
db:migrate, on the other hand, executes migration code which will be
dismissed by later migrations. db:migrate also waits for seconds to allow
to interrupt migrations if it is not favorable to run them on a running
server, but db:setup is obviously executed on a instance which is not
running yet, and the wait is unnecessary.
db:migrate has a compatibility issue. It requires a compatibility layer
to keep it working, and such one may be broken, or not provided by
dependencies such as Paperclip.
This commit replaces …
> Use db:setup instead of db:migrate when creating the database

- Running-Mastodon/Elasticsearch-guide.md
Consolidated all basic configuration steps for the ideal case to top of document, moved all memory-related and "advanced" configuration to bottom. Removed remote Elasticsearch config from document entirely and replaced it with a link to ES documentation on the topic instead.
> Rearrange documentation flow

- Running-Mastodon/Elasticsearch-guide.md
Without headless a lot of (for a server) unneeded dependencies needs be installed (on Debian stretch), like icon sets and x11-utils. Elasticsearch works without problems when you only install openjdk-8-jre-headless (that has much less dependencies).
> apt install openjdk-8-jre-headless

- Running-Mastodon/List-of-Rake-tasks.md
Add documentation for rake task to remove accounts that no longer exist on their home instance.
> Add mastodon:maintenance:purge_removed_accounts

- Running-Mastodon/Production-guide.md
As Mastodon temporaliry saves uploaded content to memory and disk (if
/tmp is a disk), unlimiting client max body size makes the server
vulnerable to DoS attack.
cc: @Gargron
> Limit client max body size in the nginx configuration example

- Using-Mastodon/Apps.md
mastodon-jfx is a desktop client for Mastodon written in kotlin using TornadoFX. It is designed for power tooters, particularly ones with multiple accounts spanning multiple instances. It is currently in an Alpha state. It is not yet feature-complete and the Look & Feel is in progress.
> Add mastodon-jfx to Apps list

- Using-Mastodon/Apps.md
Reason: app is no longer on the Play Store
> Remove Tootaloo from apps list

- Using-the-API/API.md
Per [a discussion elsewhere], the `only_media` query param does not work
on the home timeline API.
[a discussion elsewhere]: https://github.com/tootsuite/mastodon/issues/6603#issuecomment-383099654
> The only_media query param is public and tag only

- Contributing-to-Mastodon/Translating.md
From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
> Remove redundant `--`

- Running-Mastodon/Docker-Guide.md
As discussed in #591, docker will refuse to run the `mastodon:setup` step without some configuration file present.
> Adding copy config step

- Using-the-API/API.md
https://bidule.menf.in/api/v1/statuses/82725 is an example of a valid status even though it contains a null url field. Either my application should reject this, or the API should explicitely allow it.
> Update nullable of url in Status

- Using-the-API/API.md
`in_reply_to_id` and `in_reply_to_account_id` can be null in a reply. I think this behavior is counterintuitive and should be documented.
> [Event.Status] Add note on in_reply_to(_account)_id

- Using-Mastodon/Apps.md
The link to the official Halcyon instance was broken and was replaced by one provided by a third party.
The link to the Halcyon account on Mastodon was outdated and was replaced by the current one.
> Refreshed Halcyon entry in Apps.md

- Using-Mastodon/Apps.md
As Github has been bought by Microsoft,I've decided to move the Halcyon repository to an new open and trustworthy home.
This move is confirmed by the announcement of the official Halcyon account: https://social.csswg.org/users/halcyon/statuses/100153247871238507
Additionally this change has been noted in the old Github repository.
Please change the link to the new one.
> Changed link to Halcyon repository in Apps.md

- Using-the-API/API.md
Pleaaaaaase always update the api documentation after a mastodon release, things would be so much easier for app devs
> add documentation for muting reblogs

- Running-Mastodon/Migration-guide.md
If the Postgres username is different on the old server and the new server, then the previous migration guide was not correct. This fixes that.
> Update migration guide with better Postgres instructions

- Running-Mastodon/Updating-Mastodon-Guide.md
Making clear that this document is used to update a Mastodon instance that is not containerized with Docker, and shows a reader where to find Docker specific updating instructions, since those are not present in this document.
> Add pointer to Docker updating instructions

- Running-Mastodon/Development-guide.md
The rbenv ruby install command in the Development Guide is actually _older_ than the version in the Production Guide. This change matches the versions (2.5.1, newest, the one that already is in the Production Guide.)
> Update rbenv ruby version

- Running-Mastodon/Production-guide.md
The ordering defines the priority, and the code expects default > push > pull > mailers
> Fix sidekiq queues ordering in production guide

- Maintaining-Mastodon/Backups-Guide.md
I think this guide could use a bit more detail on how exactly to take a Mastodon dump and restore it. I found it very non-obvious (as a Postgres noob myself).
> Update Backups-Guide.md with more detailed backup/restore instructions

- Using-Mastodon/FAQ.md
This PR fixes what seems to be a typo in the English FAQ document. The FAQ mentions that you can `befollowed`, but I think that it should say `be followed` (with a space).
> Fix a typo in the FAQ.

- README.md
Group links about Installation the same way they are for After
Installation and Advanced so it's more obvious how it's cut.
> Rework the links about Installing mastodon

- Using-the-API/API.md
- Using-the-API/Streaming-API.md
The API endpoints for the direct messages timeline and the direct messages streaming weren't documented.
I added them to the documentation.
> Added direct messages to API documentation

- Running-Mastodon/Serving_a_different_domain.md
Spent quite a lot of time today figuring out what should the webfinger file contain when the simple redirect can't be easily configured. Hopefully this clears thing up.
> Added the content of .well-known/host-meta file

- Running-Mastodon/Production-guide.md
The current comment says that you need to cheese to create a new cert. However, certbot gives you the following options:
What would you like to do?
-------------------------------------------------------------------------------
1: Keep the existing certificate for now
2: Renew & replace the cert (limit ~5 per 7 days)
-------------------------------------------------------------------------------
It's not clear that renewing & replacing means to create a new one
> Clarify the certbot step for nginx

- content/en/admin/install.md
I tried to use the installation instructions yesterday and today, and i hit a couple stumbling blocks when the documentation was either out-of-date or was missing some commands. The most important one was the commands for installing the Ruby version. Since the `.ruby-version` file in the Mastodon repo was different from the one written into the documentation, `bundle` complained that the right Ruby version wasn't installed when it came time to run `bundle install`. The remaining commands i added were ones that were referenced by the documentation but seemed to be missing a code block to contain them.
Let me know if i need to change anything. Thanks!
> tweak install.md for completeness

- content/en/client/libraries.md
[mastodon-cpp](https://github.com/tastytea/mastodon-cpp) is not actively maintained anymore and has been replaced by [mastodonpp](https://schlomp.space/tastytea/mastodonpp).
> Libraries: Replace mastodon-cpp with mastodonpp.

- content/en/admin/optional/tor.md
A command was missing that's necessary to install the packages properly - the command to export the key used to sign the Tor packages from the gpg keyring to apt, which then allows apt to actually update with the tor repositories.
> Add missing command to export key from gpg to apt

- content/en/admin/install.md
Hi,
this PR fixes the `bundle config` invocations.
Running the second `bundle config` command as it currently is in the docs results in a warning:
```bash
$ bundle config set deployment 'true'
$ bundle config set without 'development test'
You are replacing the current global value of set, which is currently "deployment true"
```
Apparently the `set` subcommand has been removed and instead the value will automatically be set if supplied and returned if only the key is supplied.
> Fix 'bundle config' commands

- content/en/client/public.md
`json.dumps` converts JSON to Python string which is not what's needed here. If `json.dumps` is used, `statuses[0]` becomes `"`.
> Change json.dumps to json.loads

- content/en/admin/troubleshooting.md
I have seen multiple server admins complained about compilation error without an error message. Usually it's just because the server has run out of memory and swap. It would be helpful to add this message into the document.
> Add troubleshooting for compilation error

- content/en/admin/troubleshooting.md
Added one line to resolve compilation error.
From my own experience, if the compilation got interrupted because of insufficient memory, the admin must clear the cache before they compile again. Otherwise it will show "Everything's OK, nothing to do", but the assets are compiled.
> Further improve troubleshooting page

- content/en/admin/install.md
```
root@ubuntu:# systemctl enable mastodon-*
Failed to enable unit: Unit file mastodon-\x2a.service does not exist.
root@ubuntu:# systemctl enable mastodon-web mastodon-sidekiq mastodon-streaming
Created symlink /etc/systemd/system/multi-user.target.wants/mastodon-web.service → /etc/systemd/system/mastodon-web.service.
Created symlink /etc/systemd/system/multi-user.target.wants/mastodon-sidekiq.service → /etc/systemd/system/mastodon-sidekiq.service.
Created symlink /etc/systemd/system/multi-user.target.wants/mastodon-streaming.service → /etc/systemd/system/mastodon-streaming.service.
```
> fix: systemctl enable mastodon-* does not always work

- content/en/client/authorized.md
- content/en/client/guidelines.md
- content/en/client/public.md
- content/en/client/token.md
- content/en/entities/account.md
- content/en/entities/activity.md
- content/en/entities/admin-report.md
- content/en/entities/application.md
- content/en/entities/attachment.md
- content/en/entities/context.md
- content/en/entities/conversation.md
- content/en/entities/emoji.md
- content/en/entities/field.md
- content/en/entities/history.md
- content/en/entities/identityproof.md
- content/en/entities/instance.md
- content/en/entities/mention.md
- content/en/entities/notification.md
- content/en/entities/poll.md
- content/en/entities/preferences.md
- content/en/entities/relationship.md
- content/en/entities/results.md
- content/en/entities/source.md
- content/en/entities/status.md
- content/en/entities/tag.md
- content/en/entities/token.md
- content/en/methods/statuses/media.md
- content/en/spec/activitypub.md
- content/en/spec/oauth.md
- content/en/spec/security.md
As discussed in #764 there are quite a lot of outdated links in the
mastodon documentation. In basically all cases this was resolved by
simply wrapping the old plain markdown link in hugos `relref`
function[^0].
While quite a lot of links on the `/zh-cn/` also appear to be broken,
these can not be fixed by just wrapping them in `relref`[^0]. Those are
all links to `/spec/` subpages which are just not translated to `/zh-cn/`
version. Therefore, `/zh-cn/spec/` has been excluded from the automated
checking as described in the next section.
The page has been checked using the linkchecker[^1] utility. One process
is running `hugo serve` in order to see all changes in real time and
notice errors directly in your browser. In a separate command prompt the
command `linkchecker …
> Replace and fix broken links with hugos relref

- content/en/entities/relationship.md
A typo in one filename introduced itself in #801 and was brought up via this failed test: https://github.com/tootsuite/documentation/actions/runs/203082062. This fixed.
Sidenote: interestingly it doesn't fail when building it using `Hugo Static Site Generator v0.74.3/extended`-
> Fix typo in filename introduced in #801

- content/en/admin/setup.md
I asked in Discord today about which `tootctl` tasks are good to run on a regular basis (as there are a lot of cleanup jobs). It seems that `media remove` and `preview_cards remove` are the standard ones that you want to run on a regular basis (e.g. with cron). So I added this to the docs in its own section, under "Things to do after installing Mastodon."
> feat: add a section on periodic cleanup tasks

- content/en/admin/tootctl.md
Looks like this was copypasted from the previous link.
> fix: fix incorrect link to `upgrade_cli.rb`

- content/en/admin/optional/object-storage-proxy.md
Amazon has announced that it's changing S3 access style.
"path-style access" is no longer supported by buckets created after September 30, 2020.
For more information, please refer to links below.
https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingBucket.html
https://aws.amazon.com/jp/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/
> Change S3 access style

- content/en/admin/troubleshooting/index-corruption.md
Add documentation about index corruption caused by changes in collation rules, and information on how to fix it.
> Add documentation about index corruption

- content/en/admin/troubleshooting.md
without the identifier, the page on index corruption mistakenly appears at the bottom of the sidebar in its own section titled "admin-troubleshooting"
> add identifier for troubleshooting pages

- content/en/admin/troubleshooting/index-corruption.md
- emphasizes that Mastodon has to be stopped when running the script
- add `RAILS_ENV=production` in front of the `tootctl` line as it is a common mistake to run it without `RAILS_ENV` set
- mention 3.2.2 as the first release shipping the script (assuming that will be the case)
> Add more detailed instructions regarding index corruption

- content/en/user/run-your-own.md
I couldn't find any information online about what happened to them, but [their domain](http://nablahost.com/) expired and is now owned by a domain squatter.
| ![image](https://user-images.githubusercontent.com/401283/104084862-18e12380-5219-11eb-9c28-a22a77091c6a.png) | ![image](https://user-images.githubusercontent.com/401283/104084860-14b50600-5219-11eb-9e1f-27e7e0fda0d0.png) |
| --- | --- |
| Before | After |
> Remove broken link to Nablahost

- content/en/admin/tootctl.md
The options changed in v3.3.0 but the documentation was not updated at that time.
> update version history and options for `tootctl search deploy`

- content/en/admin/config.md
Explain that queries to the webfinger endpoint on the WEB_DOMAIN have to be proxied/redirected to the LOCAL_DOMAIN.
> Improve WEB_DOMAIN documentation

- content/en/admin/migrating.md
As postgres document, `pg_restore` will automatically determine the format of the dump file. But when I ran it, it failed.
Since we use `-Fc` option at `pg_dump`, writing as so in `pg_restore` would be nice.
> Add postgres dump file format specification for restore

- content/en/methods/accounts.md
- content/en/methods/apps/oauth.md
This PR ..
- makes `force_login` of type `bool`
- makes `limit` of type `number`
- moves optional parameters to bottom of table for consistency
- adds missing descriptions
> Fix `force_login` type & more

- content/en/admin/config.md
What it says on the tin, a minor but potentially confusing typo.
> Fixed 'AUTHORIZED_FETCH_MODE' typo in english

- content/en/admin/install.md
python-certbot-nginx does not exist anymore in Debian.
> Fix package name for certbot-nginx

- content/en/admin/troubleshooting/index-corruption.md
Some people asked whether they should be running the maintenance script after seeing a PgHero warning about duplicate indexes.
This PR highlights that the warning is unrelated to database index corruption.
> Add an info box about PgHero duplicate index warnings

- content/en/client/libraries.md
Problem: both Rust client library integrations are unmaintained now. They only work with old HTTP library versions (Tokio), which is a bit problematic.
The Elefren library was also deleted by the original author, fixed the link for that.
> fix(libraries): Mark all Rust libraries as unmaintained and fix link to Elefren

- content/en/admin/prerequisites.md
Update the assumed Ubuntu version to 20.04, to be consistent with the next page (install.md). This confused me when following the guide recently.
Add commands for restarting sshd, and installing fail2ban, which seemed to be implied but missing.
> [prerequisites.md] Update Ubuntu version, add missing commands

- content/en/methods/statuses/media.md
Today I read the media/ api endpoint document and was confused about the axis orientation (IE is y up or down). I initially implemented an endpoint call with the wrong Y orientation.
There is a helpful diagram but I did not see it because I foolishly scrolled down, saw the return codes section, assumed that was the end of the document, and didn't scroll further.
Edit adds a reference from the arguments section at the top to the detailed explanation of "focus" at the bottom of the page, so the next fool doesn't make the mistake I did.
> Clarify axis info on media "focus" parameter

- content/en/client/libraries.md
Per https://github.com/yks118/Mastodon-api-php/issues/4 that library is no longer maintained.
> Remove yks118/Mastodon-api-php from the PHP section

- content/en/admin/tootctl.md
The examples in the table will not work with the current version of `tootctl`.
Fixes https://github.com/mastodon/mastodon/issues/18813
> tootctl > Adjusts role name examples to title case

- content/en/admin/setup.md
- content/zh-cn/admin/setup.md
fix documentation: "admin" role should be "Admin" (per https://github.com/mastodon/mastodon/issues/18813)
> fix admin -> Admin

- content/en/admin/prerequisites.md
The configuration is basically the same as with IPv4, but with some minor changes to make them work in IPv6.
Is it perfect? Probably not. But it's better than nothing.
> Add iptables-configuration for IPv6

- content/en/client/libraries.md
The Mastodon WordPress API no longer exists - https://github.com/L1am0/mastodon_wordpress_api
> Remove dead PHP link

- content/en/admin/install.md
I installed Mastodon 4.0.2 yesterday on Ubuntu 22.04.1 (Nov 18th) and needed to change things a bit.
1. Had to install Ruby 3.0.4 instead of 3.0.3
2. Following the instructions installed postgres 15, so the config path was different
I also had to comment the https section of the nginx config file, as nginx failed as there were no certs specified for it... but reading the doc, I'm not sure if it was due to some particularity of my system.
> Update install instructions

- content/en/admin/setup.md
New to Mastodon, not familiar with the UI, I'm a bit dense so it took me several minutes to find this page 😂 
Hope this PR can help save a few minutes to other folks out there
> Specify where to find Site Settings page

- content/en/admin/prerequisites.md
Current firewall examples block ICMP messages, which are required for IPv4 PMTUD. This breaks some IPv4 connections that rely on working PMTUD between client and server.
This fixes #999.
> Update firewall examples to fix PMTUD issues

- content/en/admin/install.md
`yarn set version stable` yields many install errors of Javascript packages.  note https://codesti.com/issue/mastodon/documentation/931.
Setting `yarn set version classic` works around these problems and the rest of the instructions work as indicated.  `classic` appears to be required.
> Update install.md to use yarn version classic

- .github/workflows/publish.yml
Fixes #967
This Hugo upgrade causes significant changes to the static output. Manually browsing the site, I have not found any issues.
Static output: https://github.com/siggy/documentation/commit/f5b131652a7d6ec4c669e42683c11cf9567cfe57
Live sites:
- https://docs.joinmastodon.org
- https://documentation.sig.gy
- https://docs.joinmastodon.org/client/libraries/
- https://documentation.sig.gy/client/libraries/
This is a non-exhaustive list of differences.
https://github.com/siggy/documentation/commit/f5b131652a7d6ec4c669e42683c11cf9567cfe57#diff-4ab173a3f7265427b820697115f923b70b04bb1a13abb290546df951b0f4d050R121
The live pages are identical:
- https://docs.joinmastodon.org/admin/optional/object-storage-proxy/
- https://documentation.sig.gy/admin/optional/object-storage-proxy/ …
> Bump Hugo from `0.62.1` to `0.105.0`

- content/en/user/run-your-own.md
Service is owned and operated by me. I joined Mastodon recently and noticed that many providers are struggling to keep up with the demand, so I added support for Mastodon to our managed hosting platform.
https://cloudplane.org/
> Add Cloudplane to hosting providers

- content/en/admin/install.md
I'm guessing there was meant to be text there, so I added some to explain how to do it
> Added text after a colon in install.md (there was none)

- content/en/admin/optional.md
Adds links to `/admin/optional/` to not have the page be this empty.
> Add links to sub-pages for optional stuff

- .github/workflows/deploy.yml
This action will build Hugo and then deploy it to Github Pages, using the modern Github Pages workflow.
> Add a GH Action to deploy on Github Pages

- content/en/spec/activitypub.md
After discussion with a new implementer here https://socialhub.activitypub.rocks/t/what-could-be-the-reason-that-my-update-activity-does-not-work/2893, I realized that we don't currently document the need for an `updated` property when processing Update activities. This PR documents that requirement and adds some details about why it exists.
> Document requirement for `updated` timestamp on statuses when processing Update activity

- content/en/methods/filters.md
There was no 3.6 release. Server-side filtering was added in 4.0.
> Remove references to nonexistent Mastodon 3.6 in filter docs

- content/en/admin/scaling.md
- content/en/admin/tootctl.md
- content/en/admin/upgrading.md
- content/en/api/guidelines.md
- content/en/dev/routes.md
- content/en/entities/Account.md
- content/en/entities/Admin_Account.md
- content/en/entities/Admin_Report.md
- content/en/entities/Application.md
- content/en/entities/Error.md
- content/en/spec/activitypub.md
- content/en/spec/oauth.md
- content/en/spec/security.md
- content/zh-cn/admin/scaling.md
- content/zh-cn/admin/tootctl.md
- content/zh-cn/admin/upgrading.md
The current documentation still links to the `master` branch on the main mastodon repo which has been renamed to `main`.
Additionally the language on the scaling page uses `master` instead of `primary`, which I've added in a second commit. If you want to include this is up to you, but considering we use `replica` instead of `slave` for the secondary server already it makes sense to do the same for `master`
> Correct links to the main mastodon repo (master --> main)

- content/en/methods/statuses.md
Fix typo on this sentence under "See who boosted a status" https://docs.joinmastodon.org/methods/statuses/#200-ok-5
> Fix typo s/statuses/accounts

- content/en/spec/activitypub.md
Added more details in several places.
Preview: https://activitypub--mastodocs.netlify.app/spec/activitypub/
> Update ActivityPub documentation

- content/en/dev/setup.md
I'd hit into this when setting up my development environment, as I'd tried to use [Mailhog](https://github.com/mailhog/MailHog/) as my smtp server, but was seemingly not receiving any emails. I found some information that indicated that the project was using the letter opener gem, and that I needed to have sidekiq running for emails to be "delivered" (I didn't currently have it running).
- https://github.com/mastodon/mastodon/issues/3435
> feat: document the usage of Letter Opener for development emails

- content/en/admin/moderation.md
There's a lot of confusion about how suspending affects existing follow relationships and some moderators assume the follow relationships will be restored when a remote account (or entire server) is un-suspended within the 30-day time window.
> Clarify effects of suspending users and server

- content/en/dev/disclosure.md
There is a dedicaced email for security-related messages now.
> Update the disclosure page with the correct email address

- content/en/dev/code.md
This will need to be merged once https://github.com/mastodon/mastodon/pull/24906 is merged, as it includes this change
> Update the Localisation section to use the new React Intl command

- README.md
- content/en/client/libraries.md
Small addition to the README to note that this is currently a Hugo static site, for info only.
Main PR covers a large update to the libraries and implementations page:
- added a thank you to contributing projects and a CTA to let us know about updates and new libraries;
- removed outdated or archived projects, or seemingly inactive since ~2017/18 and behind on API methods;
- added large number of new projects 🎉 including new sections for IoT, Erlang, Kotlin, Nim, ObjC, TypeScript;
- updated links to projects that have moved.
Fixes #1204 fixes #1149 fixes #763 fixes #1160 
Built and tested locally with Hugo. In the future, the docs will be migrated to a different system; this PR brings this page up-to-date for the flurry of platform activity since start of 2023 in readiness for future …
> Update to libraries page following full review

- content/en/spec/security.md
Two things:
1. As per [MDN's article on `Digest`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Digest), the algo used must be passed in as well `sha-256=yourhash`
2. The hash should be calculated using base64 encoding, not hexadecimal (as I initially tried)
> fix: incorrect digest header format

- content/en/methods/accounts.md
~~I incorrectly assumed that if I didn't include the `pinned` parameter, then I'd get both pinned and unpinned messages - i.e. I assumed that it defaulted to `undefined`, or whatever.~~
~~This small change makes it clear that you can either request all the unpinned messages (default), or all the pinned ones - i.e. there is no way to get both in one request (IIUC).~~
This change makes it explicit that pinned statuses do not receive special priority in the order of the returned results.
> More explicit wording for `pinned` param default

- content/en/methods/statuses.md
Not sure if this follows the correct style or is precisely where these limits should be noted, but the intent is to save others time by documenting these hardcoded limits:
https://github.com/mastodon/mastodon/blob/99be47f8b9a051fe409690ba157789958a587d12/app/controllers/api/v1/statuses_controller.rb#L21-L24
Related: https://github.com/mastodon/mastodon/issues/25892
> Update Status method docs to include unauthenticated limits

- content/en/admin/moderation.md
There was a typo where 'suspended' was written as 'supended'.
> Fix typo in word 'suspended' in content/en/admin/moderation.md

- content/en/admin/optional/object-storage-proxy.md
One line says bucket & hostname, the next just hostname when in fact them both need to by bucket & hostname.
> Disambiguate hostnames

- content/en/client/libraries.md
This project is maintained on Drupal.org
> docs: update Mastodon for Drupal link

- README.md
Link to logo on GitHub instead of imgur
Use picture element for light/dark mode
> README.md: fix logo for light/dark mode

- content/en/admin/tootctl.md
As the title says, this updates the documentation to document the --days option to tootctl's media refresh function introduced in 4.0.0
> Add documentation for --days option to tootctl media refresh

- content/en/admin/tootctl.md
The defaults for `tootctl search deploy` batch size is actually 100, and increasing this size is what makes performance faster with lower database impact.
> Change tootctl search deploy default batch size to 100 to match reality

- content/en/entities/Account.md
this api returns just the date, no time component
fix https://github.com/mastodon/mastodon/issues/26843
> fix incorrect example for last_status_at

- content/en/methods/emails.md
/api/v1/emails/confirmation should be /api/v1/emails/confirmations (with an ending s) otherwise a 404 is returned
> Update the end point url on emails.md

- content/en/admin/elasticsearch.md
I figure it should be either `Elasticsearch` or `ElasticSearch`, consistently, but not `ElectisSearch` :)
> Fix typo and capitalization

- content/en/admin/install.md
With Ruby 3.0.6, installing Ruby dependencies fails with:
```
rbenv: version `3.2.2' is not installed (set by /home/mastodon/live/.ruby-version)
```
> Update ruby version in admin install docs

- content/en/admin/elasticsearch.md
`ES_USER` and `ES_PASS` need to be undefined when no auth should be used, other wise it uses `:` for credentials
> Fix ES sample config with no auth is user

- content/en/dev/setup.md
The documentation claimed that you log in with `admin@localhost:3000`, but the log in is actually just a fake email `admin@localhost`, without the port.
> Minor fix: Default admin user doesn't use port

- content/en/user/posting.md
This updates media limits for Mastodon 4.2, and also clarifies posting restrictions on GIF files.
> Update Media Limits for 4.2

- content/en/entities/Application.md
- content/en/entities/Instance.md
- content/en/methods/instance.md
As per: https://github.com/mastodon/mastodon/pull/28006/
> Add documentation for VAPID public key in instance metadata

- content/en/entities/MediaAttachment.md
In my tests, media attachments for which no alternate text was provided are conveyed to the API client as having a null description. I'm not sure if this is intentional but assuming it is, this updates the documentation to properly reflect that. Another solution might be to ensure the description is always an empty string when no alternate text was provided.
> Clarify the documenation to reflect that 'description' on media attachments can be null

- content/en/spec/security.md
For documentation purposes, example.com is a standard reserved domain (RFC 2606). We should use this instead of a random example-like domain belonging to somebody.
> Use example.com as example domain

- content/en/admin/config.md
Documents the environment variable added in https://github.com/mastodon/mastodon/pull/26857
> Add documentation for the ONE_CLICK_SSO_LOGIN environment variable

- content/en/admin/scaling.md
This reorganizes the documentation a little bit, add additional information about:
- the templated systemd files & how to start multiple instances
- information about the Prometheus metrics endpoint, and some key metrics to observe.
- Some reference numbers for concurrent streaming connections (this is based on my experience)
- Moved the warning about `STREAMING_CLUSTER_NUM` to the bottom of the section (since it's now two versions out of date at least).
> Improve scaling documentation for Streaming

- content/en/admin/install.md
The `src/configure` and `make` steps appear to be obsolete. You can see what those files look like at https://github.com/rbenv/rbenv/tree/master/src
The Makefile just prints this to stderr:
```
Warning: this Makefile is obsolete and kept only for backwards compatibility.
You can remove the `configure && make ...' step from your rbenv setup.
```
> Remove unnecessary steps from Ruby instructions.

- content/en/admin/moderation.md
Based off of moderator API functionality added here https://github.com/mastodon/mastodon/pull/18510
It's expected that this draft will need some attention to get details trimmed and accurate, but since it's not documented anywhere else right now it seemed apt to propose it all the same.
> Proposal for adding minimal documentation for undocumented moderation API (webhook)

- content/en/entities/StatusEdit.md
Corrects a copy/paste error from the earlier `poll` field.
> Fix the description of `media_attachments` in `StatusEdit`

- content/en/admin/troubleshooting/index-corruption.md
Assuming that this documentation is run inside the /live (Mastodon home directory), the current link is broken. 
The proposed change fixes this error and thus refers to the tootctl inside the bin directory
> Fix link to tootctl

- content/en/admin/prerequisites.md
Without `filter = sshd` and after restarting the service I see this error in Fail2Ban's logs (`/var/log/fail2ban.log`):
```
2022-11-03 11:24:36,225 fail2ban.transmitter    [1283507]: ERROR   Jail 'sshd-ddos' skipped, because of wrong configuration: Unable to read the filter 'sshd-ddos'
```
I added the statement as per [this article](https://serverfault.com/a/1050315) and it worked.
> Fixes Fail2Ban's directive

- content/en/methods/instance.md
Document the new `/api/v1/instance/translation_languages` endpoint added in https://github.com/mastodon/mastodon/pull/24037.
> Document /api/v1/instance/translation_languages

- content/en/methods/notifications.md
Fixes this issue https://github.com/mastodon/mastodon/issues/24684
The notification query param LIMIT should return 40 notifications as default & Maximum depends on the LIMIT param value as per the code in api/v1/notifications_controller.
> Fix notification query param LIMIT doc #24684

- content/en/admin/config.md
- content/zh-cn/admin/config.md
These variables are added in https://github.com/mastodon/mastodon/pull/28184 to control media batch deletion retry operations.
> Add explanation for S3 batch delete variables

- content/en/methods/apps.md
As per [the controller](https://github.com/mastodon/mastodon/blob/6e8711ff91e01212ac7c82de6349fa2b143582e2/app/controllers/api/v1/apps/credentials_controller.rb#L4) this endpoint requires and app token with the `read` scope.
> Clarify that apps verify_credentials requires app token + read

- content/en/admin/prerequisites.md
Fixes https://github.com/mastodon/documentation/issues/943 (again)
The previous PR https://github.com/mastodon/documentation/pull/969 for this setting does remove the error message, but it does so by duplicating the default sshd jail a second time with a different name, and does not enable the ddos filters as intended.
Only a single jail is needed, this PR specifies the `aggressive` mode, which includes the default filters, plus 'extra' and 'ddos' filters, per the instructions in the fail2ban config files:
```
#mode   = normal
```
```
```
> fix fail2ban sshd setup in jail.local

- content/en/admin/scaling.md
Closes #996 
Touches on using a load balancer but mostly highlights availability of `/health` endpoints.
> Add load balancing health check endpoints to scaling page

- content/en/admin/install.md
- content/en/admin/optional/object-storage-proxy.md
- content/zh-cn/admin/install.md
Resolves https://github.com/mastodon/documentation/issues/857
This PR adds temporary ["snakeoil" certificates](https://wiki.debian.org/Self-Signed_Certificate) to the nginx configurations, in both mastodon installation guide & object storage proxy setup guide, so that the subsequent `systemctl reload nginx` wound run successfully. Without this change, the subsequent `systemctl reload nginx` command runs would fail with logs lines like
```
nginx: [emerg] no "ssl_certificate" is defined for the "listen ... ssl" directive in /etc/nginx/sites-enabled/mastodon:25
```
The "snakeoil" certificates would be replaced automatically by references to the real certificates once the `certbot --nginx -d domain` command is run. The command is present in both mastodon installation guide & object storage …
> Install guide fixes

- assets/style.scss
- layouts/partials/sidebar.html
This adds a CSS-only nav menu toggle on mobile using a hidden checkbox input. On non-mobile viewports, the toggles are hidden and the menu always shows regardless of whether the checkbox is checked.
The menu is super long and on mobile, you have to scroll a long way to get to content. It's not a great user experience, especially since every page you navigate to you have to scroll the menu again.
I'm not a designer, and this design is very much functional as opposed to looking the best. I'm very open to feedback if anyone wants to help out and make it look nicer.
Here's a couple screenshots:
> Add mobile nav toggle

- content/en/admin/config.md
- content/en/admin/scaling.md
Reverts mastodon/documentation#1311 as this has not been merged in the code yet.
> Revert "Add basic Redis Sentinel documentation"

- content/en/entities/Instance.md
I'd accidentally used brackets instead of curly braces in the original PR #1342
> Fix issue with VAPID Public Key linking in Instance.md

- content/en/admin/install.md
Instructions taken from https://github.com/nodesource/distributions, which is where the scary message in the  ttps://deb.nodesource.com/setup_16.x setup script directs you.
> Update admin install instructions for node 20

- content/en/methods/accounts.md
getting an account's followers/following was changed to not require auth in v4.0, but the "required" label was still present on the Authorization header
> Remove "required" label from no-longer-required methods

- content/en/methods/accounts.md
The 'OAuth' field for the create-account request says that it wants an _app_ token. But the description of the 'Authorization' header says a user token.
Surely the app token is right, because if you haven't created an account yet, you don't _have_ a user token.
> Fix token type in account creation.

- content/en/admin/config.md
Added a paragraph about how people can check whether Mastodon is seeing users' real IPs. I don't think it's particularly important to include this information, but it seems nice.
This is sort of a follow-up to [my previous change](https://github.com/mastodon/documentation/commit/17a5e151a591d4df852bf9c8049db212b4a2649b).
> Small improvement to the TRUSTED_PROXY_IP docs.

- content/en/entities/Instance.md
The entity used for `/api/v2/instance` returns the streaming URL as `streaming`, not `streaming_api`.
> Fix incorrect property name `streaming_api` for the `Instance` entity

- content/en/user/posting.md
I couldn't find any documentation of under what condition my replies are shown in my followers' Home feeds and I noticed a lot of other people are confused about this as well (cf [this post & its replies](https://social.jvns.ca/@b0rk/111890684193270196#.)), so here's a documentation update that explains how it works.
The 3 specific things that I found the most confusing were:
1. A new post you make which starts with an `@mention` is **not** considered a reply (unlike how it works on Twitter)
2. Some other Fediverse software (like maybe Pleroma) will show all your replies on the Home timeline, regardless of whether the follower follows both of the people in the conversation
3. I've often heard that if you want your replies to not be shown on the Home timeline, you need to post them as …
> Update documentation with Home feed visibility for replies

- content/en/admin/config.md
When using S3 compatible object stores to save attachments, object-level ACLs must be enabled. If they are not enabled, attaching pictures to toots will fail. For some object stores, the error message does not indicate the root cause of the problem.
Unfortunately it is likely that people will accidentally disable ACLs when first setting up Mastodon. This is because both AWS S3 and Google cloud storage disable object-level ACLs by default. The GUIs for creating buckets recommend somewhat strongly that they should not be enabled.
For example, [the AWS docs say](https://docs.aws.amazon.com/AmazonS3/latest/userguide/about-object-ownership.html)
> we recommend that you disable ACLs except in unusual circumstances
And the creation UI looks like this:
It appears I'm not the only person who has …
> Document that S3 ACLs must be enabled

- content/en/methods/reports.md
This report category was was added in mastodon/mastodon#23941
> Add documentation for `legal` report category

- content/en/admin/optional/captcha.md
The original text didn't exactly make it clear to what kind of people the use of hcaptcha was problematic
> Added clarification about blind/low-vision people to captcha.md

- content/en/admin/migrating.md
- New guidance to update the mastodon database user password
- Instructions to copy over the Redis database
- Added new flag to improve pg_restore performance
- A suggestion to copy the SSL certificates over
- Added the commands needed to complete the migration along with an optional command for Elasticsearch.
> Updated the migrating.md document

- content/en/methods/announcements.md
Per https://github.com/mastodon/mastodon/issues/27310, the `with_dismissed` parameter on the announcements API is not actually implemented and is ignored.
Closes #1317
> Removed unused (not implemented) query parameter.

- content/en/entities/Translation.md
The `poll` attribute is an object, not an array, and is optional.
`id`s are strings, not integers.
The attribute is called `spoiler_text` and not `spoiler_warning`.
> Fix docs of the Translation entity

- content/en/entities/Admin_DomainBlock.md
- content/en/methods/admin/domain_blocks.md
When creating a domain block, if there is already a domain block rule for the domain, then the existing block is returned. This documents that behavior.
I've also documented the `digest` property which was added in https://github.com/mastodon/mastodon/pull/29092
> Update admin/domain_blocks to include conflict response

- layouts/partials/footer.html
When I was working on https://github.com/mastodon/documentation/pull/1425 I was getting errors from this line.
I am not a hugo expert and genuinely have no idea what I'm doing here, however I found that with huge latest version (0.124.1) installed locally the error was solved by this change. I note that the build script here is specifically using an older version ... where presumably this error doesn't occur?
> Use `.Path` instead of `.File.Path` when surrounded by `with .File` block

- content/en/entities/MediaAttachment.md
Had a payload in the wild where `preview_url` was `null` and the method that generates this value can certainly return `nil` if none of its conditions are met: 
https://github.com/mastodon/mastodon/blob/d326ad0ed9a2e874213c9313f25b973638e4b94d/app/serializers/rest/media_attachment_serializer.rb#L30-L38
Also both TootSDK and IceCubesApp have this property as nullable.
> Mark MediaAttachment.preview_url, blurhash as nullable

- content/en/methods/notifications.md
See https://github.com/mastodon/mastodon/pull/31008
It feels strange to make such a change withouth amending the version history. But since this has not been officially released yet, I hope it is fine :confused:
> Remove flag that no longer exists.

- content/en/entities/NotificationRequest.md
`from_account` should be `account`. The example below is correctly using `account` already.
Also `notifications_count` is a string in the API response.
> Fix `NotificationRequest` fields

- content/en/admin/install.md
- content/en/admin/prerequisites.md
The current docs indicate that Ubuntu 20.04 is required. 20.04 LTS will reach its EOL in less than a year, and I'd suggest that we shouldn't advise server owners to configure a new 20.04 server.
The current instructions work unchanged with Ubuntu 22.04 LTS, so I've simply updated the requirements.
See also this discussion on reddit: https://www.reddit.com/r/Mastodon/comments/1e8283s/more_current_os_versions/
> Update Ubuntu requirements

- content/en/entities/DomainBlock.md
Fix #1487, work around an error in the rendering of a {{< type shortcode in the autogenerated Table of Content of a page.
> Change {{< type shortcode to {{%

- layouts/_default/single.html
- layouts/index.html
- layouts/partials/footer.html
Hugo v0.123.0 deprecated `.Page.File.Lang`, see its release notes: https://github.com/gohugoio/hugo/releases/tag/v0.123.0 . Instead, `.Page.Language.Lang` should be used now.
This PR accordingly patches the relevant places in
* layouts/_default/single.html
* layouts/index.html
* layouts/partials/footer.html
> Fix #1490, Hugo deprecating `.Page.File.Lang`

- README.md
Added note about using latest hugo release. Some distributions and package managers may not be at the latest version, and this could cause a build error. See [hugo intallation](https://gohugo.io/installation/linux/#repository-packages).
> Note on hugo latest release

- README.md
Everybody knows what Hugo is, right? Alright, I still had to search for the project's repository before I could start hacking on `mastodon/documentation`.
This PR adds a link to Hugo's repo in the `mastodon/documentation` README to spare everyone the indirection. (It is a rebased version of an earlier PR with the same effect, #1500).
> Add link to Hugo's repo in README

- content/en/methods/accounts.md
This is required for the query param to be accepted using form url encoding.
> Add missing array syntax to follow lanagues query param

- content/en/entities/NotificationPolicy.md
- content/en/entities/V1_NotificationPolicy.md
- content/en/methods/notifications.md
This replaces `/api/v1/notifications/policy`, which was deprecated in https://github.com/mastodon/mastodon/pulls/31343
I am not quite sure in which state to leave the V1 documentation, as it's already in use, but was never actually released and might not be in the final version.
> Add documentation for `/api/v2/notifications/policy`

- content/en/methods/oauth.md
The docs said that if using an authorization code when requesting an oauth token, the `scope` parameter needed to match the one given when obtaining that code. We were made aware that this is not (or no longer) the case. In fact, whatever is passed in `scope` simply gets ignored in this case. The response will always just include the scope(s) originally requested.
This behavior is coming straight from the `doorkeeper` gem. We document this here, because it is a crucial to third-party app authentication, but we do not control when and if this changes between `doorkeeper` releases. So this paragraph here might have been correct at one point.
> Clarify `scope` parameter of oauth token creation

- content/en/admin/config.md
- content/en/admin/install.md
Documentation for https://github.com/mastodon/mastodon/pull/30090
Merge as part of Mastodon 4.3 release
> Add config for MASTODON_USE_LIBVIPS

- content/en/entities/Status.md
Add a link in the attribute description of `reblog` for the `Status` API entity which was reported missing by @nikclayton.
> Fix #1523, add missing link to `entities/Status`

- content/en/admin/config.md
- content/en/admin/scaling.md
Adds documentation for using Redis Sentinels based on the original in #1311.
Only this time, the changes have already been merged.
I also added some missing environment variables related to redis and some explanations / clarifications.
> Redis sentinel docs

- content/en/admin/config.md
This is my suggestion to deprecate `REDIS_NAMESPACE` in 4.3.
We will have to remove it at some point and even though our migration plan is not yet fully fleshed out, I believe we should discourage new installations from using it as to not make the problem even bigger.
> Deprecate redis namespace

- content/en/methods/grouped_notifications.md
Also fixes a few URLs that were still referencing `v2_alpha`
> Add documentation for `/api/v2/notifications/:group_key/accounts`

- content/en/user/run-your-own.md
The link to DigitalOcean marketplace leads to nowhere, and there doesn't appear to be a replacement on DigitalOcean's site.
> Remove outdated reference to DigitalOcean 1-click

- content/en/admin/config.md
It was only added in the development version, and removed afterwards without reaching any (pre-)release.
> Remove documentation for `REGEXP_TIMEOUT` environment variable

- content/en/admin/config.md
It is not just `REDIS_SENTINEL_USER` but `REDIS_SENTINEL_USERNAME`.
> Fix typo in redis sentinel env var names

- content/en/admin/install.md
This brings the installation instructions up-to-date with the upcoming 4.3 release and the current stable releases of the two operating systems.
I changed some punctuation, version numbers, removed commands that are no longer necessary and simplified a couple of others.
The biggest changes are due to changes in the two operating systems:
* `adduser --disabled-login` no longer sets a shell for the user it creates. I changed it to `--disabled-password` which should have roughly the same effect (preventing remote logins) as the old `--disabled-login`.
* We have a couple of open issues and PRs because nginx needs to access assets and was no longer able to in newer OS versions because default permissions on home directories changed. I added a step to add the `www-data` user to the `mastodon` …
> Update installation instructions for 4.3 on Ubuntu 24.04 and Debian 12

- content/en/methods/oauth.md
I noticed this when reviewing #1445 but thought this was on purpose (confusing special characters used by different markup languages here :man_facepalming:).
> Fix typo in oauth api parameters

- content/en/entities/Notification.md
By clear about the situations in which the `update` status type is sent.
> fix: Replace "interacted with" with "reblogged"

- content/en/entities/Instance.md
- content/en/methods/instance.md
Related to https://github.com/mastodon/mastodon/pull/33153
> Add media attachment description limit

- content/en/entities/Notification.md
See https://github.com/mastodon/mastodon/issues/33411
> Fix incorrect `relationship_severance_event` attribute name in notifications documentation

- content/en/admin/config.md
Adds a callout box mentioning that CORS headers must be set if WebFinger requests are being redirected to support a customised WEB_DOMAIN value.
This requirement is not called out in the text (only the nginx config example next to it), and is non-obvious enough that, anecdotally, many servers do not implement it properly.
See: https://github.com/mastodon/mastodon/issues/26995
> Draw attention to CORS requirements for WebFinger

- content/en/entities/ScheduledStatus.md
Noticed this TODO when doing other change.
Not sure how to add nuance here between "the request level rate limit" and "the model level rate limit". First pass here.
> Add explanation of rate limit in scheduled status entity

- .github/workflows/deploy.yml
- config.toml
Noticed some deprecation noise on recent actions output - https://github.com/mastodon/documentation/actions/runs/12369534530
For hugo itself -- stepped up version by version locally checking for deprecation output and verifying the site looked the same after build at each version bump. Was able to go all the way to latest with only one config/deprecation change needed.
For the GH actions stuff, bumped to latest for each, which should handle deprecations, but not sure how to verify these other than opening PR and watching.
Do we get a per-PR preview build w/ the gh pages config?
> Update hugo to version 0.140.2, GH actions to latest

- content/en/entities/Account.md
- content/en/methods/accounts.md
Documentation for new `attribution_domains` API attribute proposed in https://github.com/mastodon/mastodon/pull/32730.
> Add documentation for `attribution_domains`

- content/en/admin/optional/object-storage.md
After encountering issues with setting up S3 myself, I deem the default provided on `S3_ENDPOINT` as misleading. Before, I have been using a custom hostname, only, resulting in lots of warnings in the log reading `expected :endpoint to be a HTTP or HTTPS endpoint`.
> provide default matching expected format

- content/en/entities/WebPushSubscription.md
- content/en/methods/push.md
For PR https://github.com/mastodon/mastodon/pull/33528
> Add standard push notifications

- content/en/client/authorized.md
From what I can tell, the `scope` parameter is only used on the `client_credentials` grant type, it is **not** used for `authorization_code`, where the access token gains the approved scopes during the authorization request.
I would've thought Doorkeeper would raise an error here, but it accepts the parameter (but does nothing with it)
Related doorkeeper issue: https://github.com/doorkeeper-gem/doorkeeper/issues/1765
> Fix invalid scope parameter on authorization code token request

- content/en/user/network.md
while working on https://github.com/mastodon/documentation/pull/1610 , i noticed that the search prefix terms were not documented. They are included in a screenshot, but that doesn't have much explanation, and there are some hidden options that are a cause of repeated "TIL you can do xyz on masto" posts. The image also doesn't have alt text, so i added a reference to "see below" for our screenreader-using friends :)
> Search terms + fetching behavior

- content/en/admin/elasticsearch.md
ElasticSearch is bundled with its own version of OpenJDK. Using a standalone JDK is not necessary or recommended.
> Remove installation of OpenJDK

- content/en/entities/Instance.md
`#{registrations-reason_required}` should be `{#registrations-reason_required}`.
> Fix typo in anchor definition

- content/en/entities/Account.md
According to the documentation, and inspecting API output from mastodon.social, the `attribution_domains` property is only included in `CredentialAccount`, not `Account`.
This document has example JSON output for both `Account` and `CredentialAccount`, and `attribution_domains` appears in both.
Correct the `Account` example and remove `attribution_domains`.
> fix: Remove "attribution_domains" from vanilla account example

- content/en/methods/accounts.md
Previous documentation only mentioned the `source` property. `update_credentials` actually returns a `CredentialAccount`.
See https://github.com/mastodon/mastodon/blob/82688387a8d19906371a6dd4af64e5b662031603/app/controllers/api/v1/accounts/credentials_controller.rb#L18
> fix: `update_credentials` returns a `CredentialAccount`

- content/en/methods/search.md
Previous documentation did not state that resolve parameter is also used to request resolving an HTTPS URL query into a status.
Fix #1644
> Clarify usage of resolve parameter if query is URL.

- layouts/_default/single.html
- layouts/index.html
using time tag helps with accessibility, e.g screen readers. 
see: https://shkspr.mobi/blog/2020/12/making-time-more-accessible/
> feat: use `<time>` tag

- content/en/methods/accounts.md
[https://docs.joinmastodon.org/methods/accounts/#unpin](https://docs.joinmastodon.org/methods/accounts/#unpin) points to two things, a deprecated API route and a non-deprecated API route. This PR separates the two by changing the non-deprecated's ID to `unendorse`
> Fix the link in "Unfeature account from profile"

- content/en/api/oauth-scopes.md
- content/en/methods/oauth.md
I noticed I hadn't yet documented this feature coming in 4.4.0 (current `main`) following a conversation on Mastodon.
This also fixes some previously broken links in the OAuth Authorization Server metadata section.
> Document the /oauth/userinfo endpoint

- content/en/admin/optional/tor.md
In the setup guide for setting up onion services I got some errors on Debian 12, so I've added a notice with a reference to the official TOR Docs* in the Docs, as those will be up-to-date for installing the Tor services over their repository.
*https://support.torproject.org/apt/tor-deb-repo/
> Added reference to official Tor docs

- content/en/admin/elasticsearch.md
Elasticsearch might eat LOTS of RAM, so users with limited resources might want to set a RAM limit for Elasticsearch's JVM.
> Add RAM limiting config to Elasticsearch setup instructions

- content/en/admin/prerequisites.md
I ran into the problem on a Debian server. This might happen with Ubuntu in the future as well?
Solution taken from: https://github.com/fail2ban/fail2ban/issues/3292
> Add fail2ban solution for systems that only log with systemd.

- content/en/methods/oauth.md
The version history on OAuth Authorization Server Metadata was squished into one line instead of being multiple
cc @andypiper
> Minor formatting fix for OAuth documentation

- content/en/entities/AccountWarning.md
If a moderation warning action is `delete_statuses` then the `status_ids` property is also populated.
Note that a client cannot fetch or otherwise act on these statuses, as they have already been deleted, even if the associated appeal is successful.
> feat: Note that `delete_statuses` moderation warning is irrevocable

- content/en/methods/push.md
[PushToFCM](https://github.com/tateisu/PushToFCM) is archived and points to SubwayTooterAppServerV2.
> Replace archived Web Push example server

- content/en/client/public.md
https://mastovue.glitch.me doesn't work anymore because Glitch ended project hosting (see https://blog.glitch.com/post/changes-are-coming-to-glitch/).
> Remove broken link

- content/en/entities/Announcement.md
It doesn't appear to be an actual attribute. 
https://github.com/mastodon/mastodon/blob/main/app/serializers/rest/announcement_serializer.rb
> Remove Announcement#published

- content/en/entities/Account.md
- content/en/methods/accounts.md
Fixes #1483
Adds Account roles documentation. Referenced `account_serializer`, `credential_account_serializer`, `role_serializer` and associated models.
Adds missing fields to API responses in Account method documentation.
> Account roles and fields update

- content/en/admin/install.md
Updates the installation instructions for upstream package removals and renames that happened years before the required versions of ubuntu and debian in the doc. Also updates the list of system packages to remove redundant dependencies that are already pulled in by the explicitly installed packages.
**System repositories** section:
- `apt-transport-https` was removed upstream years ago; this is just a transitional package that doesn't install anything, since `apt` already supports https.
**System packages** section:
- `libxslt1-dev` pulls in `libxml2-dev`
- `git-core` was renamed `git`
- `build-essential` pulls in `g++` and `gcc`
- `protobuf-compiler` pulls in `libprotobuf-dev`
- `libreadline6-dev` was renamed `libreadline-dev`
- `libreadline-dev` pulls in `libncurses-dev` (also renamed …
> Update package names and dependencies in "Installing from source"

- content/en/admin/install.md
Tiny change to increase the version number of Debian we recommend.
I verified that all the steps still work unchanged on Debian 13.
> Recommend current Debian stable

- content/en/entities/Account.md
- content/en/entities/Notification.md
- content/en/entities/QuoteApproval.md
- content/en/entities/Status.md
- content/en/methods/accounts.md
- content/en/methods/grouped_notifications.md
- content/en/methods/preferences.md
- content/en/methods/push.md
- content/en/methods/statuses.md
- content/en/spec/activitypub.md
While Mastodon 4.4 added support for verifying and displaying quote posts through a new `quote` attribute on [`Status`](https://docs.joinmastodon.org/entities/Status/#quote) and [`StatusEdit`](https://docs.joinmastodon.org/entities/StatusEdit/#quote) entities, Mastodon 4.5 adds support for viewing simplified *quote policies*, setting quote policies on outgoing posts, writing quote posts, getting quote notifications, listing quotes of one of your posts, revoking quotes, and being notified when a post you have quoted has been edited.
The new APIs described below are available starting with [Mastodon API version](https://docs.joinmastodon.org/entities/Instance/#api_versionsmastodon) 7.
- the [`Status`](https://docs.joinmastodon.org/entities/Status/) entity has a new `quote_approval` …
> Add documentation for Mastodon 4.5 quote post features

- content/en/user/moving.md
The "previously exported CSV files" link was targeting the main homepage instead of the section within the `/user/moving/` page. I spot checked the pl, ja, zh-cn `user/moving.md` files and didn't see an equivalent link, but I could have missed it.
> Fix link on /user/moving/

- content/en/methods/statuses.md
Fix s/accounts/statuses.
I also suspect that DEFAULT_STATUSES_LIMIT applies here too, so instead of default 40, should be 20. I didn't test/check this so I'll update this PR if it's wrong 🙇‍♂️
> Fix limit description for "See quotes of a status"
