Using-the-API/API.md

"Fix" https://github.com/tootsuite/mastodon/issues/1454

Correct API accounts actions http method

---

Using-Mastodon/FAQ.md

Add the sound a mastodon makes to the FAQ.

---

Using-Mastodon/List-of-Mastodon-instances.md

Adding description for mstdn.io

---

Running-Mastodon/Heroku-guide.md

Copied from https://github.com/tootsuite/mastodon/pull/1345 .

Updated Heroku deploy guide.

---

Running-Mastodon/Production-guide.md
Using-Mastodon/List-of-Mastodon-instances.md

Adding an Apache configuration example

---

Contributing-to-Mastodon/Translating.md

Fixed broken links due to documentation being in its own repo now.

Fix broken links

---

Using-Mastodon/Apps.md

Add my experimental Windows 10 app ;)

Update app list

---

Contributing-to-Mastodon/Translating.md

Even more working links

---

Running-Mastodon/Production-guide.md

DB connections fail with the default pg_hba.conf.

made pg_hba.conf addition with ident for Ubuntu 16.04

---

Using-Mastodon/Apps.md

I am not a developer of mastodon.el, I just think it important that people find this application. Thanks.

Added client for emacs to the list of applications

---

Using-Mastodon/List-of-Mastodon-instances.md

I was missing gateway configuration on my server. Sorry about creating extra work you y'all!

IPv6 is working on oulipo.social again

---

Running-Mastodon/Production-guide.md
Using-Mastodon/User-guide.md

Hi. Here is a summary of my changes:
- Fixed two grammatical errors in **Production-guide.md**. Changed "setup" to "set up" in two places.
- Fixed an incorrect filename for the Follow icon in the **User-guide.md** file.

Fixed grammatical error and incorrect icon filename

---

Running-Mastodon/Resources-needed.md

fixed two small typos in the name of the file

Fix typo (ressources -> resources)

---

Using-Mastodon/Apps.md

Add Capella to apps

---

Running-Mastodon/Resources-needed.md

Fix bandwidth units for oc.todon.fr

---

Running-Mastodon/Production-guide.md

commit of mastodon here https://github.com/tootsuite/mastodon/commit/e17f9d5e1ad63dc61085b4288f349f8a6f75361d

Use the united command for daily task

---

Running-Mastodon/Heroku-guide.md

This is not quite step-by-step yet, but at least indicates that you need to do more than just adding the Mailgun add on.

Updated Mailgun instructions

---

Using-the-API/API.md

Add mastodon.js as a Browser JS lib

Add mastodon.js

---

Running-Mastodon/Resources-needed.md

These are the stats I have on-hand, not sure how to find median bandwidth in/out.

Added for Docker instance resources

---

README.md
Running-Mastodon/Docker-Guide.md
Running-Mastodon/Maintenance-Tasks.md
Running-Mastodon/Production-guide.md

This is connected to https://github.com/tootsuite/mastodon/pull/2026

Import from main repo README

---

Using-the-API/API.md

Although there is explanation also at the beginning, I think that it is more convenient to add a detailed explanation.
[tootsuite/mastodon/app/controllers/api/v1/accounts_controller.rb#L39](https://github.com/tootsuite/mastodon/blob/9783d8b6c074c371acd466c17acf0b21f82af296/app/controllers/api/v1/accounts_controller.rb#L39)

Add query parameters to followers

---

Running-Mastodon/Resources-needed.md

To give interested admin an idea of what expected costs might be.

Add cost estimate column

---

Running-Mastodon/Docker-Guide.md

A replacement PR for https://github.com/tootsuite/mastodon/pull/1937 .

Updates Docker Update Instructions for git

---

Running-Mastodon/Production-guide.md

Maybe, We should `git fetch` when upgrade new version.

add git fetch line to upgrade section

---

Running-Mastodon/Resources-needed.md

Corrected "https://mastodon.technllogy" to "https://mastodon.technology"

Small URL error in Resources-needed.md

---

Using-the-API/API.md

I implemented mastodon4j for Java, Kotlin. :smile:
https://github.com/sys1yagi/mastodon4j

Add mastodon4j. 

---

Using-the-API/API.md

Added available library for C#

---

Using-the-API/API.md

Although there is explanation also at the beginning, I think that it is more convenient to add a detailed explanation.
Continuation of #89.

Add max_id, since_id, limit to API

---

Running-Mastodon/Production-guide.md

This notably fixes potential issues like this one https://github.com/tootsuite/mastodon/issues/1665

Production guide: add support for let's encrypt in the nginx config

---

Using-the-API/API.md

I implemented a mastodon module for Haskell, [Hastodon](https://github.com/syucream/hastodon). :D

Add a Haskell lib

---

Using-the-API/API.md

Add library C#

---

Running-Mastodon/Development-guide.md

See https://github.com/tootsuite/mastodon/issues/2316

Development: Fix bundle install instructions and expand on running rails

---

Running-Mastodon/PgBouncer-guide.md

I wrote a PgBouncer guide, just in case it's useful to others. I found there were lots of gotchas and surprises, so hopefully this will be helpful.
Notes:
- I assume no Docker
- I assume Ubuntu/Debian
- I'm using the md5-based password system becuase I couldn't get the other ones to work ¯\\\_(ツ)_/¯

Add PgBouncer guide

---

Running-Mastodon/Tuning.md

This is a new option as documented here: https://github.com/tootsuite/mastodon/blob/bb04a9be52e005fb8bbeef22e5b8d30f0d202903/.env.production.sample#L90-L92

Update Tuning.md to mention `STREAMING_CLUSTER_NUM`

---

Running-Mastodon/Production-guide.md

Reverts tootsuite/documentation#122

Revert "Avoid hard-coding ciphers into configuration"

---

Running-Mastodon/PgBouncer-guide.md

Fix typo in BgBouncer-guide.md

---

Using-the-API/API.md

Add alternative Golang library

Add Golang library

---

Using-the-API/API.md

This commit changes the list of available libraries to a table, similar to the one used for the list of apps in documentation/Apps.md. Soon more libraries for the same language will appear and a table will handle it better. It also sorts the libraries in ascending order (case insensitive) by language.

Adds table for libraries

---

Running-Mastodon/Serving_a_different_domain.md

Add extensive documentation for WEB_DOMAIN, as the feature is ill-documented and may be confusing.

Document how to use WEB_DOMAIN along with common pitfalls

---

Running-Mastodon/Production-guide.md

Instructions for installing on CentOS

---

Running-Mastodon/Scalingo-guide.md

- better limitation docs
- add instructions for adding custom domains
- add upgrading instructions

scalingo guide: major improvements

---

Running-Mastodon/PgBouncer-guide.md

fix order of username and password when generating hash with md5sum
https://pgbouncer.github.io/config.html#authentication-file-format

fix section "Configuring userlist.txt" of PgBouncer-guide.md

---

Using-the-API/API.md

Add apex salesforce library

---

Running-Mastodon/Administration-guide.md

This way you can assign admininistration priviledges to users on some configurations

Updated Administration-guide.md

---

Running-Mastodon/Alternatives.md

This is the configuration we use on https://generous.horse and it includes the Cache-Control and Referrer-Policy headers.

Update Apache configuration a bit

---

Using-the-API/API.md

This should resolve issue #79. I've included all 4 PHP libraries
mentioned in that issue, per the conversation in PR #150.

Add PHP API Libraries

---

Contributing-to-Mastodon/Translating-Github-Cheat-Sheet.md
Contributing-to-Mastodon/Translating.md

* Improve documentation about translation.
* Update path description about javascript translations.
Depends on tootsuite/mastodon#2835
Resolves #217.

Translation doc

---

Using-Mastodon/FAQ.md
Using-Mastodon/FAQ_ESP.md

Since there were technical issues with PR #165, I'm doing a separate PR
based on that work. This one doesn't delete the original FAQ, and it includes a link at the top of the English FAQ as requested by @wxcafe.

Adding Spanish FAQ by @Ametlles

---

Running-Mastodon/Production-guide.md

See discussion in #136. /cc @nolanlawson

Updates for Docker documentation

---

Using-Mastodon/Apps.md

Add Flantter to Apps

---

Running-Mastodon/Production-guide.md

This reflects https://github.com/tootsuite/mastodon/commit/d5cabfe5c65ac29d2f9c151b46c01a9fd885a9e0.

Add dependencies for CLD3

---

Running-Mastodon/Customizing.md

This change reflects https://github.com/tootsuite/mastodon/commit/af6a84da147f4230807b37c64bc09760e6ab5055.

Update "Customizing your instance" according to a change in Mastodon

---

Using-Mastodon/Apps.md

I also added some guidelines in a comment section (only displayed when editing this file).

Reorganization of the Apps.md page

---

Running-Mastodon/Development-guide.md

These are the steps I followed to get my Mastodon development environment set up on my Mac.

Mac development environment instructions

---

Running-Mastodon/Development-guide.md

Things I bumped into while setting up and them updating my dev env.

dependencies and webpacker

---

README.md
Running-Mastodon/Nanobox-Guide.md

To be merged after Nanobox Support is merged in the main repo: https://github.com/tootsuite/mastodon/pull/1709

Document Nanobox Usage

---

Using-Mastodon/User-guide.md
Using-the-API/API.md

See https://github.com/tootsuite/mastodon/pull/3271

Document "mute boosts" functionality

---

Using-the-API/API.md

Based on:
* Add language detection [#1772](https://github.com/tootsuite/mastodon/pull/1772)
* Fix forgotten to include language attribute in statuses JSON [#3209](https://github.com/tootsuite/mastodon/pull/3209)

Adds language to Status

---

Using-the-API/API.md

@Kimik0 noticed the endpoint was missing. Read more about it here #265

Adds notifications/dismiss/:id (Fixes #265)

---

Running-Mastodon/Production-guide.md
Using-the-API/API.md

nginx config by removing overly specific configuration options
that confuse more than they help

Fix API docs by adding missing attributes and methods, fix example

---

Running-Mastodon/Alternatives.md

Added the needed ProxyPass exceptions for 1.4.1

Update on apache configuration

---

Using-Mastodon/Apps.md

Adding Fastoot app to Browser add-ons/extensions in Apps.md.

Adding Fastoot to app lists

---

Using-Mastodon/FAQ.md

Updating the FAQ to include information on hiding all content from a given instance.

Add information on blocking instances

---

Running-Mastodon/Development-guide.md

Added a small fix for something that annoyed me for ages CSRF errors and no cookies, all came down to this missing part in the docs, so here is the fix.

small doc fix

---

Running-Mastodon/Production-guide.md

I ran through this three times picking up errors in documentation and now, from start to finish it will work, with these small tweaks.

added some missing info to prod.

---

Running-Mastodon/Docker-Guide.md

Mention that we can use prebuilt images in docs.

---

Using-Mastodon/Apps.md

It's a very very very simple bot script, written in Python.

Add simpleMastodonBot to list of bots

---

README.md
Running-Mastodon/List-of-Rake-tasks.md

Resolved #330. Added new documentation of the list of Rake tasks.

Add list of Rake tasks

---

Running-Mastodon/Docker-Guide.md

this has been out of date for a few months now

remove bit about cronjobs

---

Running-Mastodon/Production-guide.md

A short guide to Let's Encrypt certificate tool installation, certificate generation and automated renewal.

Add Let's Encrypt section 

---

LICENSE

Reverts tootsuite/documentation#349
Need agreement from contributors first.

Revert "Fix #262 - Use GNU Free Documentation License"

---

Running-Mastodon/Production-guide.md

g++ doesn't provide necessary package for gem.

replace g++ for build essential

---

LICENSE
Running-Mastodon/Production-guide.md

I rewrote the Mastodon Production Guide with better structure and clarity.
Work on the rewrite was done on my own repo:
https://github.com/staticsafe/mastodon-documentation

Complete rewrite of Mastodon Production Guide

---

Using-Mastodon/Apps.md

Changed details:
- /halcyon-for-mastodon => /halcyon
- @neet@mastodon.social => @halcyon@mastodon.social

Update Apps.md: Changed Halcyon's repositry

---

Running-Mastodon/Updating-Mastodon-Guide.md

This is guide is for use with my recently merged Production Guide.
Feedback welcome.

Adding my new updating Mastodon guide

---

Running-Mastodon/Production-guide.md

gcc-6 isn't a valid package name

"gcc-6" should just be "gcc"

---

Using-Mastodon/Apps.md

Fluffy-broccoli is a `#NowPlaying` bot, with a funny name.

Add fluffy-broccoli to the list of bots

---

Running-Mastodon/Migration-guide.md

When I migrated toot.cafe to a new server, I had to mostly figure this stuff out by myself (e.g. which files were obligatory to copy over, how to do a Postgres dump/load, etc.). Hopefully this migration guide can help the next person figure out what they need to do! 😄

Add migration guide

---

Using-the-API/API.md

See Gargron's comment here: https://github.com/tootsuite/mastodon/issues/4610#issuecomment-322803055

Clarify how sensitive and spoiler_text are related

---

Using-the-API/OAuth-details.md

Explain how to do OAuth in detail

---

Using-Mastodon/Apps.md

added my image tooting bot to the list of apps
https://botsin.space/@kanami_ibuki/

add mastodon-img-bot to apps

---

Using-Mastodon/Apps.md

translation tool for mastodon
https://ostatus.taiyolab.com/@t_trace/113466

add oxpecker to apps

---

Running-Mastodon/Production-guide.md

Update ruby version

---

Using-Mastodon/Apps.md

Also removed one, that can't be downloaded (anymore) and fix sorting

Added a few more Android apps

---

Running-Mastodon/Security-Guide

This is a guide I wrote to help with securing a Mastodon server and related accounts.

Add Security Guide

---

Running-Mastodon/Administration-guide.md

The all listed commands is seemingly bash commands, but the 2nd and latter is command for rails command prompt.

add note for commands.

---

Running-Mastodon/Customizing.md

This is to document the merged pull request:
https://github.com/tootsuite/mastodon/pull/4643

Add an explanation how to customize link to source code

---

Running-Mastodon/Customizing.md

This should be consistent with the behavior as of 2.0.0.rc2.

Add instructions for custom themes

---

Running-Mastodon/Docker-Guide.md

Anonymous git URL is easier for the initial git clone

---

Using-the-API/Streaming-API.md

See https://github.com/tootsuite/mastodon/issues/5839.

Document streaming URL for local statuses

---

Running-Mastodon/Production-guide.md

We're not security expert and we shouldn't have to be. So it's better to tell people where to go to find some help.

Putting an end to the endless cryptonerd comments by recommending people to use the Mozilla SSL Configuration Generator

---

Running-Mastodon/Customizing.md

variables.scss path has been changed.
ref tootsuite/mastodon#5336

Fix variables.scss path

---

Using-Mastodon/FAQ.md

Maybe someone can explain activitypub a bit

We use now activirtypub

---

Using-the-API/API.md

this glosses over the use of data or external uris with paperclip because it's kind of complicated and I don't have the best handle on the edge-cases, but I can take a look at that if it seems useful.

improve documentation of form-data uploads

---

Using-Mastodon/User-guide.md

Adding what can and can't go into a hashtag character-wise, the part where hashtag searches update in real time, how to pin hashtag searches, and what doesn't make it into a hashtag search (unlisted toots, toots not known to your instance).

Overhaul and more detail for the hashtags section

---

Using-Mastodon/User-guide.md

The image is still the old NSFW, instead of the new eye icon. I don't know how to change that - can anyone advise?

Changing NSFW to CW where I can

---

Using-the-API/API.md

to keep methods and entities sorted alphabetically.

Moves List and Lists around

---

Using-Mastodon/Apps.md

python3 based code recreating the look and feel of pink Minitel 3615 ULLA, but acting as a Mastodon client

Minitel mastodon client... looking like 3615 ULLA

---

Using-Mastodon/Apps.md

Add SPIP plugin

---

Using-Mastodon/FAQ.md

Much of this was written back when Eugen was more or less It and contains a lot of first-person stuff. I changed a couple of these to make it project-person, but wanted to get some feedback on that first. I can do a more extensive edit on those through the documentations if it's okay to do.

Add Liberapay link and revise some sentences

---

Running-Mastodon/List-of-Rake-tasks.md

I add two new commands:
- make_mod to give moderator privileges to an user
- revoke_staff to revoke admin or moderator privileges
Thanks :bowing_man:

Add two privileges functions

---

Running-Mastodon/Production-guide.md

Updates Ruby version to 2.5.0. Installation fails otherwise.

Update ruby version from 2.4.2 to 2.5.0

---

Running-Mastodon/Production-guide.md

Add libpam0g-dev to Ubuntu package dependencies

---

Running-Mastodon/Production-guide.md

Enables bundler multicore support for quicker processing.

Enable bundler multicore support

---

Running-Mastodon/Production-guide.md

Reverts tootsuite/documentation#534

Revert "Add libpam0g-dev to Ubuntu package dependencies"

---

Running-Mastodon/List-of-Rake-tasks.md

Typo in List-of-Rake-tasks.md

---

Running-Mastodon/Elasticsearch-guide.md

Fix small typo

---

Running-Mastodon/List-of-Rake-tasks.md

Not sure about the wording, but wanted to get this one on the list.

Added chewy:deploy to list of rake tasks

---

Using-the-API/API.md

i was gonna post an issue on the main mastodon repo requesting support for idempotency keys, turns out they're already supported but not documented 😬

document idempotency-key header

---

Using-Mastodon/Apps.md

Cause CLI apps and Bots overlapped, I mostly combined them under Command line clients.
Also a few other minor issues.

 Resorted apps, clarify what's FOSS and proprietary, and ToC 

---

Using-the-API/API.md

add "fields" in Account and source in verify_credential
add "fields_attributes" in update_credential

(API) profile metadata fields

---

Contributing-to-Mastodon/Translating.md

translaing  -- translating on paragraph 108

Typo on paragraph #106 & 108

---

Running-Mastodon/Resources-needed.md

Added statistics for another smallish instance.

Add MSPSocial.net

---

Running-Mastodon/Production-guide.md

Change Ruby version.

---

Using-the-API/API.md

marked as nullable for backward compatibility, hope thats ok

add 'bot' flag to account entity

---

Running-Mastodon/Docker-Guide.md

See issue #7782
Also fixes the issue of "rake" being not found.

Prepend "bundle exec" to rake commands in docker

---

Using-the-API/API.md

GET /api/v1/suggestions
DELETE /api/v1/suggestions/:account_id

(API) Follow suggestions

---

Running-Mastodon/Production-guide.md

Update production guide for Ubuntu 18.04

---

Using-Mastodon/Apps.md

Added the [Whalebird](https://whalebird.org/) desktop app.

Whalebird app

---

Running-Mastodon/Production-guide.md

The first line wasn't changed to 18.04.

Still some 16.04 stuff

---

Running-Mastodon/Docker-Guide.md

I've deployed from master and didn't checkout a stable release tag....

Follow production best practice

---

Running-Mastodon/Production-guide.md

I just realized I could not do certain things from a sudo. I needed to be root via `sudo /bin/bash`. I know this is a trival issue, but I am intermediate at handling the terminal and needed to know this.

Show How To Become Root

---

Running-Mastodon/Tuning.md

Feel free to edit it to use better words

Add Docker instructions for "Using a separate Redis for the Rails cache"

---

Using-the-API/API.md

When I read the spec I wasn't sure what this meant and had to test it.

Filters: improve documentation

---

README.md

Heya,
This page is really handy for mastodon instance admin and I'm sad I didn't see it before. Add the link so people don't miss it.
Cheers,
Daniel

Add a link of the Updating guide in the Readme

---

Using-Mastodon/Apps.md

Added FeedToMastodon to apps

---

Running-Mastodon/Tuning.md

I run jemalloc on all my instances, as do some other admins.

Update Tuning.md to add jemalloc instructions

---

Using-Mastodon/FAQ.md

ActivityPub is now a recommended standard

---

Using-the-API/API.md

Everyone needs to know about the most important endpoint.

Add Custom Emojis endpoint to the docs.

---

Running-Mastodon/Vagrant-guide.md

Updating documentation based on merged pull request https://github.com/tootsuite/mastodon/pull/8706

update default vagrant domain

---

Using-the-API/API.md

Typo fix in API.md

---

Using-Mastodon/FAQ_ESP.md

WIP (made a review until "mobile/desktop/CLI apps section")

update Spanish FAQ_ESP.md. 

---

content/en/admin/tootctl.md

ref: https://github.com/tootsuite/mastodon/pull/12810

add remote_only emoji purge to tootctl

---

content/en/methods/timelines/streaming.md

streaming should be nested under timelines

fix copy-paste error

---

config.toml
content/en/admin/config.md
content/en/entities/account.md
content/en/entities/announcement.md
content/en/entities/notification.md
content/en/methods/announcements.md
content/en/methods/notifications.md
content/en/methods/oembed.md
content/en/methods/proofs.md
layouts/_default/single.html

update for 3.1

---

content/en/entities/identityproof.md

Fix IdentityProof `updated_at` description

---

content/en/admin/config.md
content/zh-cn/admin/config.md

Resolves https://github.com/tootsuite/documentation/issues/810

Add DB_SSLMODE to config page

---

content/en/dev/setup.md

This has tripped me up a few times, so having this in the documentation would save me a Google search. :slightly_smiling_face:

fix: explain Postgres error when creating a dev environment

---

content/en/dev/setup.md

Add pre-requisites instructions for dev setup

---

content/en/entities/filter.md
content/en/user/moderating.md

Following the clarification made at tootsuite/mastodon/pull/15139, update documentation (both for API and user interface) too.

Mention that filters targetting home timeline also affects lists

---

content/en/admin/install.md

Just so you can copy and paste the code without even thinking what you're trying to do

Update, we need to install Ruby 2.7.2

---

content/en/admin/install.md

Reverts tootsuite/documentation#829
Too early
Fix tootsuite/mastodon#15253

Revert "Update, we need to install Ruby 2.7.2"

---

content/en/admin/install.md

Reverts tootsuite/documentation#830

Revert "Revert "Update, we need to install Ruby 2.7.2""

---

content/en/admin/config.md
content/en/admin/install.md

Improves #852, but doesn't fix it.

Slight improvements for admin docs

---

content/en/admin/config.md
content/en/admin/install.md

Reverts tootsuite/documentation#856

Revert "Slight improvements for admin docs"

---

content/ja/user/run-your-own.md
content/zh-cn/user/run-your-own.md

Remove broken link to Nablahost

---

content/en/admin/moderation.md

This PR reflects details of the new moderation options including:
- Mark sensitive
- Limit
- Freeze
- Suspend (including new 30 day cooling off period)

Updated individual moderation info to reflect new moderation options.

---

content/en/admin/troubleshooting/index-corruption.md

added links to the SQL `REINDEX` and CLI `reindexdb` commands

point towards how to avoid index corruption

---

content/en/admin/troubleshooting/index-corruption.md

- Typo fix : "duplicate" ➤ "duplicates"
- Typo fix : "chose" ➤ "choose"
- Typo fix : "occuring" ➤ "occurring"

Typo fixes

---

content/en/user/run-your-own.md

Update Hosting Providers

---

content/en/admin/prerequisites.md

`whitelist` should not be used as it isn't inclusive.

Use more inclusive language.

---

content/en/admin/setup.md
content/zh-cn/admin/setup.md

See https://github.com/mastodon/documentation/pull/972#issuecomment-1304655676

Admin -> Owner

---

content/en/user/run-your-own.md

Missing closing double quote
https://github.com/mastodon/documentation/pull/980 broke the build: https://github.com/mastodon/documentation/actions/runs/3414266091/jobs/5681993727
This should fix it

Fix broken markup

---

content/en/admin/scaling.md

Added more context based on the Discord discussion with Claire.

Add ingress queue & update pull docs

---

content/en/admin/install.md

[mastodon/mastodon/main/.ruby-version
](https://github.com/mastodon/mastodon/commit/113dd90aa3e8dd930fa343a2dea52e64bf63eb06#diff-1bdb3279c7718f7037156f83c80eb81c58d37b286e027219e055b76249082264)
https://github.com/mastodon/mastodon/pull/18028

Correct ruby version to 3.0.4

---

content/en/user/posting.md

Added instructions on how to set default post privacy, and added more detail on how to change privacy for any one post.

Update posting.md (Issue #1041)

---

content/en/user/preferences.md

Clarify what "posting defaults" means and make it more likely that users will find these settings with a search.

Update preferences.md (Issue #1041)

---

content/en/admin/optional/tor.md

Fixes dead link for [this link](https://matt.traudt.xyz/posts/2017-12-02-dont-https-your-onions/)

Fix dead link

---

content/en/methods/filters.md

whole_word is a boolean, not a string

---

content/en/admin/tootctl.md

Adds documentation from this PR https://github.com/mastodon/mastodon/pull/22149/files landing in the next Mastodon stable 4.1.0

feat: adds new flags to tootctl media remove

---

content/en/admin/config.md

Signed-off-by: aimuz <mr.imuz@gmail.com>

fix: config cdn link

---

content/en/admin/troubleshooting.md

Fixed this issue - https://github.com/mastodon/mastodon/issues/16378

Add troubleshooting for sandboxing mode

---

content/en/methods/push.md

based on conversation in https://github.com/mastodon/mastodon/issues/25729

Clarify WebPush documentation and it's relationship to proprietry services

---

content/en/client/authorized.md

Just a minor text update for this page. Changed the header "**Use** Safety Features" to "**User** Safety Features".

Spelling correction - User Safety Features

---

content/en/admin/optional/tor.md

Because that's what they're called, see https://community.torproject.org/onion-services/.

Rename 'hidden' to 'onion'

---

content/en/entities/Admin_Cohort.md
content/en/entities/Admin_Dimension.md
content/en/entities/FeaturedTag.md
content/en/entities/FilterResult.md
content/en/entities/Reaction.md
content/en/entities/Role.md
content/en/entities/StatusEdit.md
content/en/methods/admin/canonical_email_blocks.md

I have been busy with parsing the markdown docs in order to get something resembling an api spec, and I found some inconsistencies and other issues, which could not be fixed in my parser code. Here's what I found so far.

Fixed some consistency issues in the documentation

---

content/en/admin/elasticsearch.md

Follow up from #1279
Related to https://github.com/mastodon/mastodon/issues/27034

Redirect the old ES page to the new one

---

content/en/admin/install.md

Update install.md postgres 16 instead of 15

---

content/en/admin/install.md

Fix installation instructions pointing to pre-releases

---

content/en/methods/accounts.md

Add documentation for https://github.com/mastodon/mastodon/pull/27667

Add documentation for `with_suspended` params

---

layouts/partials/footer.html

Removes the link and icon for Twitter from the footer of the page.

Remove Twitter from Footer

---

content/en/user/preferences.md

Remove reference to language detection

---

content/en/methods/statuses.md

Addresses Mastodon Documentation issue: https://github.com/mastodon/documentation/issues/1239

An important parameter is missing from the API doc on editing a post #1239

---

content/en/admin/prerequisites.md

Opens the default port used for HTTP/3

Allow incoming HTTP/3 connections

---

content/en/entities/Translation.md
content/en/methods/statuses.md

Documentation for the new translation attributes about to be added in https://github.com/mastodon/mastodon/pull/24175.

Document new translations attributes

---

content/en/admin/install.md
content/en/admin/migrating.md

Remove nginx default site

---

content/en/entities/Relationship.md

Add documentation for `requested_by`

---

content/en/admin/config.md

Those have been introduced/changed in 4.2 but documentation was missing

Add documentation for cache buster and hcaptcha

---

content/en/entities/Notification.md
content/en/entities/RelationshipSeveranceEvent.md

Add documentation for the API additions made in https://github.com/mastodon/mastodon/pull/27511

Add documentation for the `severed_relationships` event type

---

content/en/_index.md

Few minor typos in documentation are corrected.

Fix: Typo in documentation

---

content/en/entities/Admin_Cohort.md

Fix typo in Admin::Cohort entity

---

content/en/admin/config.md

When configuring my instance, I have struggled to find the meaning and expected values of some settings.
I added the result of my research to the documentation

Add documentation for some settings

---

content/en/admin/install.md

Updated to match for Mastodon v4.2.4 release.

Install Ruby 3.2.3 from rbenv

---

content/en/user/profile.md

Profile: Mention 1MB response limit for verification

---

content/en/admin/tootctl.md

Added tootctl accounts prune help info

Update tootctl documentation to add missing argument on account - prune

---

content/en/entities/Instance.md
content/en/entities/V1_Instance.md

Mark `contact[account]` as nullable in `Instance` entity

---

content/en/entities/Instance.md
content/en/methods/instance.md

https://github.com/mastodon/mastodon/pull/29441

Add `max_pinned_statuses` property to instances.accounts

---

content/en/admin/config.md

First pass docs for https://github.com/mastodon/mastodon/pull/29831

Add doc for AR encryption env vars

---

content/en/entities/Role.md

- Convert id to String
- Convert permissions to String

Fix incorrect types in Role

---

content/en/methods/accounts.md
content/en/methods/statuses.md

See https://github.com/mastodon/mastodon/pull/27871

Add documentation for `GET /api/v1/accounts` and `GET /api/v1/statuses`

---

content/en/admin/config.md

Documentation for https://github.com/mastodon/mastodon/pull/30717
Merge as part of Mastodon 4.3 release.

Add config for REDIS_DRIVER

---

content/en/user/posting.md

Documenting https://github.com/mastodon/mastodon/pull/26264

Add AVIF to allowed image types

---

content/en/methods/notifications.md

See https://github.com/mastodon/mastodon/pull/31191

Add documentation for `/api/v1/notifications/unread_count`

---

content/en/entities/Instance.md
content/en/methods/instance.md

This attribute was added in https://github.com/mastodon/mastodon/pull/30205

Add documentation for the new `icons` attribute in `/api/v2/instances`

---

content/en/entities/Notification.md
content/en/methods/notifications_alpha.md

Some examples are missing but most of it should be there.

Add documentation for `/api/v2_alpha/notifications`

---

content/en/admin/config.md

Related to https://github.com/mastodon/mastodon/pull/31998

Added documentation for additional OTEL service name customization

---

content/en/admin/config.md

Introduced here: https://github.com/mastodon/mastodon/pull/32056

Document new environment variable

---

content/en/admin/config.md

It took me to look through the code to understand what it does. Hoping this is a better description.

Clarify the description of ALLOW_PRIVATE_ADDRESSES

---

content/en/admin/install.md

apt.postgresql.org defaults to v17 for Ubuntu 24.04.

Update postgresql version in path

---

content/en/admin/scaling.md

https://github.com/mastodon/mastodon/pull/32908

Docs to match #32908 - REPLICA_DB_TASKS / REPLICA_PREPARED_STATEMENTS

---

content/en/admin/optional/object-storage.md

fixed incorrect minio example policy

---

content/en/admin/config.md

See https://github.com/mastodon/mastodon/pull/33342

Document the new `QUERY_LOG_TAGS_ENABLED` variable

---

content/en/methods/streaming.md

Document Authorization header for WebSocket API

---

content/en/admin/config.md

See https://github.com/mastodon/mastodon/pull/33734

Add documentation for the new prometheus exporter feature

---

content/en/spec/activitypub.md

Add missing properties from toot: namespace

---

content/en/api/guidelines.md

See https://github.com/mastodon/mastodon/pull/34262#event-16973822851

Add keeping up with deprecations to API user guidelines

---

content/en/entities/Instance.md

Fix `terms_of_service` URL and `privacy_policy` URL having incorrect nullable flags

---

content/en/entities/TermsOfService.md
content/en/methods/instance.md

Ref: mastodon/mastodon#33993
___
Fixes MAS-398

Add documentation for `GET /api/v1/instance/terms_of_service`

---

content/en/entities/Quote.md
content/en/entities/ShallowQuote.md
content/en/entities/Status.md
content/en/entities/StatusEdit.md
content/en/spec/activitypub.md

Document https://github.com/mastodon/mastodon/pull/34370 and https://github.com/mastodon/mastodon/pull/34479
---
Fixes MAS-370, MAS-413

Add documentation for quote posts support

---

content/en/entities/Instance.md

Documentation for https://github.com/mastodon/mastodon/pull/34576

Add documentation for `configuration[limited_federation]` to Instance entity

---

content/en/entities/Account.md

Per discussion in https://github.com/mastodon/mastodon/issues/34661

fix: Move `attribution_domains` to `source` property

---

content/en/admin/tootctl.md

Update documentation for `tootctl self-destruct`

---

content/en/entities/Rule.md

Documentation for https://github.com/mastodon/mastodon/pull/34494

Add documentation for server rules translations

---

content/en/entities/Tag.md
content/en/methods/tags.md

Add documentation for `POST /api/v1/tags/:id/feature` and related

---

content/en/admin/troubleshooting.md

I made two mistakes during the migration to Mastodon v4.3 and had a stressful time. I want to share my solutions and the possible causes. 
1. WebUI was not working, but API was
2. Error during database migration because I run pg_bouncer and forgot to add DB_PORT=
This might also be useful to others, esp. admins who google the symptoms.

Add troubleshooting hints about DB migration error and missing webUI error

---

content/en/client/intro.md

- add 429 to list of 4xx status codes on the client intro page
- Updated `Unprocessed` to `Unprocessable Content`

Add 429 to to list of status codes

---

content/en/methods/blocks.md

Add description to blocks method

---

content/en/entities/Quote.md
content/en/entities/ShallowQuote.md

Fix incorrect attribute in `Quote` and `ShallowQuote` entity documentation

---

content/en/entities/Application.md
content/en/methods/apps.md

Another round of checking against the current code (serialisers and models) to bring us back into line with reality.

Improvements for the Application entity and methods

---

content/en/admin/tootctl.md

remove long-retired --skip-sign-in-token from docs

---

content/en/admin/moderation.md

As requested in #1262, this adds a section on server blocklists, including description, import, and export.

Update moderation.md with blocklist info, fixes #1262
